/**
 * The static image maps for every applied tenant, and the one this build uses.
 *
 * GENERATED by `pnpm onboard --tenant <slug> --apply`. Do not edit.
 *
 * Separate from ./index.ts because this file reaches `.webp` modules: the
 * config barrel has to stay importable from `node:test`, this one does not.
 * The slug is resolved once, there, so both barrels can never disagree.
 */
import { TENANT_SLUG } from './index';

import { TENANT_MENU_MEDIA as menuMediaCoffeeStory } from './coffee-story/menu-media.generated';
import { BUNDLED_CUTOUTS as cutoutsCoffeeStory } from './coffee-story/product-media.generated';

export type TenantMediaSlot = {
  readonly menuMedia: Readonly<Record<string, number>>;
  readonly productMedia: Readonly<Record<string, number>>;
};

const MEDIA: Readonly<Record<string, TenantMediaSlot>> = {
  'coffee-story': {
    menuMedia: menuMediaCoffeeStory,
    productMedia: cutoutsCoffeeStory,
  },
};

// Object.hasOwn and not a bare index: a slug is a key into a plain object, so
// an inherited property name would otherwise read as a bundled tenant.
const selected = Object.hasOwn(MEDIA, TENANT_SLUG) ? MEDIA[TENANT_SLUG] : undefined;
if (!selected) {
  throw new Error(`apps/customer has no bundled media for "${TENANT_SLUG}". Re-run \`pnpm onboard --tenant ${TENANT_SLUG} --apply\`.`);
}

export const TENANT_MEDIA: TenantMediaSlot = selected;
