/**
 * Every tenant this checkout has applied, and the one this build is for.
 *
 * GENERATED by `pnpm onboard --tenant <slug> --apply`. Do not edit.
 *
 * Asset-free on purpose: only JSON is imported here, so `node:test` can reach
 * anything that reads a tenant without a `.webp` transform. The static import
 * maps live in ./media.ts.
 *
 * `EXPO_PUBLIC_TENANT` picks the tenant and is inlined into the bundle at
 * build time (publicly readable, which a slug is fine to be). Unset with one
 * tenant applied resolves to it; unset with several throws right here, because
 * a build that guesses ships one shop's menu under another shop's name.
 */
import { selectTenantSlot, type TenantSlotIdentity } from '@platform/domain';

import brandCoffeeStory from './coffee-story/brand.json';
import menuCoffeeStory from './coffee-story/menu.json';
import modulesCoffeeStory from './coffee-story/modules.json';

export type TenantSlot = TenantSlotIdentity & {
  readonly brand: unknown;
  readonly modules: unknown;
  readonly menu: unknown;
};

/** Applied slugs, sorted. More than one is the point of this layout. */
export const APPLIED_TENANT_SLUGS: readonly string[] = ['coffee-story'];

const SLOTS: Readonly<Record<string, TenantSlot>> = {
  'coffee-story': {
    slug: 'coffee-story',
    brand: brandCoffeeStory,
    modules: modulesCoffeeStory,
    menu: menuCoffeeStory,
  },
};

export const TENANT_SLOT: TenantSlot = selectTenantSlot({
  app: 'kiosk',
  slots: SLOTS,
  requested: process.env.EXPO_PUBLIC_TENANT,
});

export const TENANT_SLUG: string = TENANT_SLOT.slug;
