/**
 * The static image maps for every applied tenant, and the one this build uses.
 *
 * GENERATED by `pnpm onboard --tenant <slug> --apply`. Do not edit.
 *
 * Separate from ./index.ts because this file reaches `.webp` modules: the
 * config barrel has to stay importable from `node:test`, this one does not.
 * The slug is resolved once, there, so both barrels can never disagree.
 */
import { TENANT_SLUG } from './index';

import { TENANT_MENU_MEDIA as menuMediaCoffeeStory } from './coffee-story/menu-media.generated';
import brandLogoCoffeeStory from '../../assets/tenants/coffee-story/brand/logo.png';
import { TENANT_MENU_MEDIA as menuMediaJuniperBaseDemo } from './juniper-base-demo/menu-media.generated';
import brandLogoJuniperBaseDemo from '../../assets/tenants/juniper-base-demo/brand/logo.png';
import { TENANT_MENU_MEDIA as menuMediaStillpointBuilders } from './stillpoint-builders/menu-media.generated';
import brandLogoStillpointBuilders from '../../assets/tenants/stillpoint-builders/brand/logo.png';

export type TenantMediaSlot = {
  readonly brandLogo: number;
  readonly menuMedia: Readonly<Record<string, number>>;
};

const MEDIA: Readonly<Record<string, TenantMediaSlot>> = {
  'coffee-story': {
    brandLogo: brandLogoCoffeeStory,
    menuMedia: menuMediaCoffeeStory,
  },
  'juniper-base-demo': {
    brandLogo: brandLogoJuniperBaseDemo,
    menuMedia: menuMediaJuniperBaseDemo,
  },
  'stillpoint-builders': {
    brandLogo: brandLogoStillpointBuilders,
    menuMedia: menuMediaStillpointBuilders,
  },
};

// Object.hasOwn and not a bare index: a slug is a key into a plain object, so
// an inherited property name would otherwise read as a bundled tenant.
const selected = Object.hasOwn(MEDIA, TENANT_SLUG) ? MEDIA[TENANT_SLUG] : undefined;
if (!selected) {
  throw new Error(`apps/kiosk has no bundled media for "${TENANT_SLUG}". Re-run \`pnpm onboard --tenant ${TENANT_SLUG} --apply\`.`);
}

export const TENANT_MEDIA: TenantMediaSlot = selected;
