/**
 * The static image maps for every applied tenant, and the one this build uses.
 *
 * GENERATED by `pnpm onboard --tenant <slug> --apply`. Do not edit.
 *
 * Separate from ./index.ts because this file reaches `.webp` modules: the
 * config barrel has to stay importable from `node:test`, this one does not.
 * The slug is resolved once, there, so both barrels can never disagree.
 */
import { TENANT_SLUG } from './index';

import { TENANT_MENU_MEDIA as menuMediaCoffeeStory } from './coffee-story/menu-media.generated';

export type TenantMediaSlot = {
  readonly menuMedia: Readonly<Record<string, number>>;
};

const MEDIA: Readonly<Record<string, TenantMediaSlot>> = {
  'coffee-story': {
    menuMedia: menuMediaCoffeeStory,
  },
};

const selected = MEDIA[TENANT_SLUG];
if (!selected) {
  throw new Error(`apps/kiosk has no bundled media for "${TENANT_SLUG}". Re-run \`pnpm onboard --tenant ${TENANT_SLUG} --apply\`.`);
}

export const TENANT_MEDIA: TenantMediaSlot = selected;
