import { StyleSheet } from 'react-native';
import { type BrandTokens } from '@platform/ui';

export const createRewardSheetStyles = (tokens: BrandTokens) => StyleSheet.create({
  perkSheet: { minHeight: '62%', maxHeight: '90%', borderTopLeftRadius: tokens.radius.lg, borderTopRightRadius: tokens.radius.lg, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.xl, gap: tokens.spacing.lg },
  helpSheet: { borderTopLeftRadius: tokens.radius.lg, borderTopRightRadius: tokens.radius.lg, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.xl, gap: tokens.spacing.lg, height: '88%', maxHeight: '88%', justifyContent: 'space-between' },
  helpScroll: { flex: 1 },
  helpScrollContent: { gap: tokens.spacing.lg, paddingBottom: tokens.spacing.sm },
  helpDoneButton: { minHeight: 56, borderRadius: tokens.radius.pill, backgroundColor: tokens.textPrimary, alignItems: 'center', justifyContent: 'center' },
  helpDoneText: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 18 },
  referralSheet: { flex: 1, marginTop: 78, borderTopLeftRadius: tokens.radius.lg, borderTopRightRadius: tokens.radius.lg, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.lg, gap: tokens.spacing.xl },
  sheetTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.lg },
  sheetBadges: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  sheetTierBadge: { borderRadius: tokens.radius.md, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.md, paddingVertical: tokens.spacing.md },
  sheetTierText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  lockedBadge: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.sm },
  lockedBadgeText: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  closeButton: { width: 48, height: 48, borderRadius: 24, backgroundColor: tokens.surface, alignItems: 'center', justifyContent: 'center' },
  sheetTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 38, lineHeight: 44 },
  sheetBody: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16, lineHeight: 24 },
  sheetSpacer: { flex: 1 },
  referralPointsBadge: { borderRadius: tokens.radius.md, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.md, paddingVertical: tokens.spacing.md },
  referralPointsText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  referralTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 42, lineHeight: 48 },
  referralBody: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16, lineHeight: 24 },
  referralLinkCard: { minHeight: 72, borderRadius: tokens.radius.lg, borderWidth: 1, borderColor: tokens.secondary, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.lg, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  referralLink: { flex: 1, borderRadius: tokens.radius.pill, backgroundColor: tokens.surface, color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 15, padding: tokens.spacing.md },
  referralFootnote: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 18 },
  referralDivider: { height: 1, backgroundColor: tokens.secondary },
  referralPendingTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 24 },
  referralEmpty: { minHeight: 66, borderRadius: tokens.radius.lg, borderWidth: 1, borderColor: tokens.secondary, alignItems: 'center', justifyContent: 'center' },
  referralEmptyText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  pendingReferral: { minHeight: 62, borderRadius: tokens.radius.lg, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pendingReferralCode: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  pendingReferralStatus: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13, textTransform: 'capitalize' },
  helpRule: { borderTopWidth: 1, borderTopColor: tokens.secondary, paddingTop: tokens.spacing.lg, gap: 3 },
  helpRuleTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  helpRuleBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14, lineHeight: 20 },
  pressed: { opacity: 0.66 },
  rowPressed: { opacity: 0.76, transform: [{ scale: 0.99 }] },
});
