import { StyleSheet } from 'react-native';
import { mixHex, type BrandTokens } from '@platform/ui';

export const createRewardStatusStyles = (tokens: BrandTokens) => StyleSheet.create({
  statusHero: { alignItems: 'center', gap: tokens.spacing.md },
  haloSegment: { position: 'absolute', width: 6, height: 18, borderRadius: 3 },
  haloCenter: { position: 'absolute', width: 140, height: 140, alignItems: 'center', justifyContent: 'center' },
  rewardMark: {
    width: 104,
    height: 104,
    borderRadius: 38,
    borderWidth: 5,
    borderColor: tokens.accent,
    backgroundColor: tokens.surface,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '45deg' }],
  },
  rewardMarkCompact: { width: 32, height: 32, borderRadius: 11, borderWidth: 2 },
  rewardMarkHeart: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 50, transform: [{ rotate: '-45deg' }] },
  rewardMarkHeartCompact: { fontSize: 15 },
  statusName: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 42, marginTop: -22 },
  statusChip: { borderRadius: tokens.radius.md, backgroundColor: tokens.accent, paddingHorizontal: tokens.spacing.lg, paddingVertical: tokens.spacing.md },
  statusChipText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14, textAlign: 'center' },
  statusCarryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: tokens.spacing.sm },
  statusCarry: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  progressChevronOpen: { transform: [{ rotate: '180deg' }] },
  progressDropdown: { width: '100%', overflow: 'hidden' },
  progressCard: { width: '100%', borderWidth: 1, borderColor: tokens.secondary, borderRadius: tokens.radius.md, padding: tokens.spacing.lg, gap: tokens.spacing.md, backgroundColor: tokens.surfaceElevated },
  progressHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.md },
  progressTitleWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  progressTitle: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 13 },
  progressRemaining: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12 },
  progressTrack: { height: 7, borderRadius: tokens.radius.pill, backgroundColor: tokens.secondary, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: tokens.radius.pill, backgroundColor: tokens.primary },
  progressMilestones: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressCheck: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 22 },
  progressLock: { color: tokens.secondary, fontFamily: tokens.fontBody, fontSize: 22 },
  perkRow: {
    minHeight: 82,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    borderBottomWidth: 1,
    borderBottomColor: tokens.secondary,
    paddingHorizontal: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
  },
  perkIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: tokens.surface, alignItems: 'center', justifyContent: 'center' },
  perkIconLocked: { backgroundColor: tokens.surface },
  perkIconText: { color: tokens.primary, fontFamily: tokens.fontDisplay, fontSize: 24 },
  perkLabel: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16, lineHeight: 22 },
  nextTierBanner: {
    minHeight: 112,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surface,
    padding: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
  },
  crownMark: { width: 76, height: 76, borderRadius: 22, backgroundColor: tokens.surfaceElevated, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-4deg' }] },
  crownText: { color: tokens.primary, fontFamily: tokens.fontDisplay, fontSize: 52 },
  nextTierCopy: { flex: 1, gap: 4 },
  nextTierName: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 34 },
  nextTierThreshold: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 17 },
  earnList: { gap: tokens.spacing.md },
  earnRow: {
    minHeight: 80,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.surface,
    paddingHorizontal: tokens.spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing.lg,
  },
  earnRowComplete: { opacity: 0.42 },
  earnLabel: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 17 },
  earnLabelComplete: { textDecorationLine: 'line-through', color: tokens.textMuted },
  earnValue: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14, backgroundColor: tokens.surface, paddingHorizontal: 12, paddingVertical: 10, borderRadius: tokens.radius.md },
  earnValueComplete: { backgroundColor: tokens.surface, color: tokens.textMuted },
  explainerCard: { marginTop: tokens.spacing.md, padding: tokens.spacing.xl, borderRadius: tokens.radius.lg, backgroundColor: tokens.surface, gap: tokens.spacing.md },
  explainerTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 18 },
  explainerBody: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14, lineHeight: 21 },
  cashCard: { minHeight: 230, borderRadius: tokens.radius.lg, overflow: 'hidden', padding: tokens.spacing.xl, shadowColor: tokens.textPrimary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: tokens.elevation.card, shadowRadius: 24, elevation: 5 },
  cashCardPressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  cashHint: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  cashBalance: { position: 'absolute', top: tokens.spacing.xl, right: tokens.spacing.xl, color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 34 },
  cashBottom: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  // The wordmark is set lower case by design; it used to be typed that way in
  // the screen, which made the casing a property of one tenant's name.
  cashBrand: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 33, textTransform: 'lowercase' },
  // Same reason as cashBrand: the all-caps line was typed in caps in the
  // screen, so the casing travelled with one tenant's word for stored value.
  cashSubbrand: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 10, letterSpacing: 1.5, textTransform: 'uppercase' },
  currencyPill: { borderRadius: tokens.radius.pill, backgroundColor: mixHex(tokens.surface, tokens.accent, 0.12), paddingHorizontal: tokens.spacing.lg, paddingVertical: tokens.spacing.md },
  currencyText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  actionRow: { minHeight: 82, borderRadius: tokens.radius.pill, backgroundColor: tokens.surface, borderWidth: 1, borderColor: tokens.secondary, paddingHorizontal: tokens.spacing.xl, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.lg },
  actionRowLabel: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 17 },
  cashActivity: { borderTopWidth: 1, borderTopColor: tokens.secondary },
  activityRow: { minHeight: 86, borderBottomWidth: 1, borderBottomColor: tokens.secondary, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.lg },
  activityCopy: { flex: 1, gap: 4 },
  activityTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  activityDate: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
  activityAmount: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  activityAmountPositive: { borderRadius: tokens.radius.md, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.md, paddingVertical: tokens.spacing.sm },
  emptyActivity: { paddingVertical: tokens.spacing.xxl, alignItems: 'center', gap: tokens.spacing.sm },
  emptyActivityTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 17 },
  emptyActivityBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
});
