import { StyleSheet } from 'react-native';
import { mixHex, type BrandTokens } from '@platform/ui';

export const createRewardBaseStyles = (tokens: BrandTokens) => StyleSheet.create({
  safeTop: { flex: 1, backgroundColor: tokens.surface },
  screen: { backgroundColor: tokens.surface },
  screenContent: { paddingTop: 0, paddingHorizontal: 0, paddingBottom: 138, gap: 0 },
  stickyNav: { backgroundColor: tokens.surface, zIndex: 3, elevation: 3 },
  whiteBody: { backgroundColor: tokens.surface, minHeight: 780 },
  demoTierBar: { paddingHorizontal: 0 },
  demoTierRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 4 },
  demoTierItem: { flex: 1, minWidth: 0, alignItems: 'center', gap: 4 },
  demoTierChip: {
    width: '100%',
    minHeight: 42,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  demoTierChipSelected: { borderWidth: 3 },
  demoTierChipLocked: { backgroundColor: tokens.secondary, borderColor: tokens.textMuted },
  demoTierChipContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 3 },
  demoTierText: { fontFamily: tokens.fontBody, fontSize: 13, textAlign: 'center' },
  demoTierPercent: { fontFamily: tokens.fontBody, fontSize: 10, lineHeight: 13 },
  demoTierArrow: { flexShrink: 0, marginTop: 15 },
  tabContent: { paddingHorizontal: tokens.spacing.lg, paddingTop: tokens.spacing.lg, gap: tokens.spacing.lg },
  tabContentCompact: { paddingHorizontal: tokens.spacing.md, paddingTop: tokens.spacing.md, gap: tokens.spacing.md },
  header: {
    minHeight: 44,
    paddingHorizontal: tokens.spacing.lg,
    paddingBottom: tokens.spacing.md,
    backgroundColor: tokens.surface,
    zIndex: 3,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerCompact: { paddingHorizontal: tokens.spacing.md },
  headerTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 22 },
  headerTitleCompact: { fontSize: 19 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  headerActionsCompact: { gap: tokens.spacing.sm },
  tierChip: {
    minHeight: 34,
    borderRadius: tokens.radius.pill,
    backgroundColor: mixHex(tokens.surface, tokens.primary, 0.11),
    paddingLeft: tokens.spacing.md,
    paddingRight: tokens.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.sm,
  },
  tierChipCompact: { minHeight: 30 },
  tierChipText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  tierChipTextCompact: { fontSize: 13 },
  helpButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: mixHex(tokens.surface, tokens.primary, 0.11),
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpButtonCompact: { width: 32, height: 32, borderRadius: 16 },
  helpText: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: tokens.textMuted,
    color: tokens.textMuted,
    fontFamily: tokens.fontBody,
    fontSize: 14,
    lineHeight: 19,
    textAlign: 'center',
  },
  tabs: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: tokens.spacing.xl,
    paddingHorizontal: tokens.spacing.lg,
    backgroundColor: tokens.surfaceElevated,
    borderBottomWidth: 1,
    borderBottomColor: tokens.secondary,
    zIndex: 2,
    elevation: 2,
  },
  tab: { alignItems: 'center', justifyContent: 'flex-end', gap: 8 },
  tabLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  tabLabelCompact: { fontSize: 13 },
  tabLabelActive: { fontFamily: tokens.fontBody },
  tabIndicator: { alignSelf: 'stretch', height: 3, borderRadius: tokens.radius.pill, backgroundColor: tokens.textPrimary },
  pointsHero: {
    minHeight: 210,
    borderRadius: tokens.radius.lg,
    overflow: 'hidden',
    padding: tokens.spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pointsCopy: { zIndex: 2, flex: 1, gap: tokens.spacing.sm },
  pointsLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 18 },
  pointsNumber: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 58, lineHeight: 66 },
  earnRatePill: {
    alignSelf: 'flex-start',
    minHeight: 36,
    borderRadius: tokens.radius.md,
    backgroundColor: 'rgba(255,255,255,0.48)',
    paddingHorizontal: tokens.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.sm,
  },
  earnRateText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 12 },
  sectionTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 25, marginTop: tokens.spacing.lg },
  rewardList: { gap: 2 },
  rewardRow: {
    minHeight: 112,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    borderBottomWidth: 1,
    borderBottomColor: tokens.secondary,
    paddingHorizontal: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
  },
  rewardRowLocked: { opacity: 0.56 },
  rewardHeart: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardCopy: { flex: 1, gap: 4 },
  rewardTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 18 },
  rewardCost: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 15 },
  lockedText: { color: tokens.textMuted },
  footnote: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 18, paddingVertical: tokens.spacing.lg },
});
