import { StyleSheet } from 'react-native';

import { colors, fonts, radius, shadow, spacing } from '@/theme/tokens';

/**
 * Every style for the Rewards tab and its sheets.
 *
 * Kept as one sheet rather than split alongside the components: the tabs, rows
 * and sheets share a great many of these, and partitioning them would either
 * duplicate values or leave a "shared" file that is most of the sheet anyway.
 * One source keeps the tab surfaces visually identical by construction.
 */
export const styles = StyleSheet.create({
  safeTop: { flex: 1, backgroundColor: colors.brand100 },
  screen: { backgroundColor: colors.brand100 },
  screenContent: { paddingTop: 0, paddingHorizontal: 0, paddingBottom: 138, gap: 0 },
  stickyNav: { backgroundColor: colors.brand100, zIndex: 3, elevation: 3 },
  whiteBody: { backgroundColor: colors.surface, minHeight: 780 },
  demoTierBar: { paddingHorizontal: 0 },
  demoTierRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 4 },
  demoTierItem: { flex: 1, minWidth: 0, alignItems: 'center', gap: 4 },
  demoTierChip: {
    width: '100%',
    minHeight: 42,
    borderRadius: radius.pill,
    backgroundColor: colors.brand50,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  demoTierChipSelected: { borderWidth: 3 },
  demoTierChipLocked: { backgroundColor: colors.ink200, borderColor: colors.ink300 },
  demoTierChipContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 3 },
  demoTierText: { fontFamily: fonts.sansMedium, fontSize: 13, textAlign: 'center' },
  demoTierPercent: { fontFamily: fonts.sansBold, fontSize: 10, lineHeight: 13 },
  demoTierArrow: { flexShrink: 0, marginTop: 15 },
  tabContent: { paddingHorizontal: spacing.md, paddingTop: spacing.md, gap: spacing.md },
  tabContentCompact: { paddingHorizontal: spacing.sm, paddingTop: spacing.sm, gap: spacing.sm },
  header: {
    minHeight: 44,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
    backgroundColor: colors.brand100,
    zIndex: 3,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerCompact: { paddingHorizontal: spacing.sm },
  headerTitle: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 22 },
  headerTitleCompact: { fontSize: 19 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  headerActionsCompact: { gap: spacing.xs },
  tierChip: {
    minHeight: 34,
    borderRadius: radius.pill,
    backgroundColor: 'rgba(110,75,122,0.11)',
    paddingLeft: spacing.sm,
    paddingRight: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  tierChipCompact: { minHeight: 30 },
  tierChipText: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 14 },
  tierChipTextCompact: { fontSize: 13 },
  helpButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(110,75,122,0.11)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpButtonCompact: { width: 32, height: 32, borderRadius: 16 },
  helpText: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: colors.ink500,
    color: colors.ink500,
    fontFamily: fonts.sansBold,
    fontSize: 14,
    lineHeight: 19,
    textAlign: 'center',
  },
  tabs: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: spacing.lg,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.ink200,
    zIndex: 2,
    elevation: 2,
  },
  tab: { alignItems: 'center', justifyContent: 'flex-end', gap: 8 },
  tabLabel: { color: colors.ink900, fontFamily: fonts.sans, fontSize: 15 },
  tabLabelCompact: { fontSize: 13 },
  tabLabelActive: { fontFamily: fonts.sansBold },
  tabIndicator: { alignSelf: 'stretch', height: 3, borderRadius: radius.pill, backgroundColor: colors.ink900 },
  pointsHero: {
    minHeight: 210,
    borderRadius: radius.md,
    overflow: 'hidden',
    padding: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pointsCopy: { zIndex: 2, flex: 1, gap: spacing.xs },
  pointsLabel: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 18 },
  pointsNumber: { color: colors.ink900, fontFamily: fonts.display, fontSize: 58, lineHeight: 66 },
  earnRatePill: {
    alignSelf: 'flex-start',
    minHeight: 36,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(255,255,255,0.48)',
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  earnRateText: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 12 },
  sectionTitle: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 25, marginTop: spacing.md },
  rewardList: { gap: 2 },
  rewardRow: {
    minHeight: 112,
    borderRadius: radius.pill,
    backgroundColor: colors.brand50,
    borderBottomWidth: 1,
    borderBottomColor: colors.ink200,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  rewardRowLocked: { opacity: 0.56 },
  rewardHeart: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: colors.warm,
    borderWidth: 1,
    borderColor: colors.brand100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardCopy: { flex: 1, gap: 4 },
  rewardTitle: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 18 },
  rewardCost: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 15 },
  lockedText: { color: colors.ink500 },
  footnote: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 12, lineHeight: 18, paddingVertical: spacing.md },
  statusHero: { alignItems: 'center', gap: spacing.sm },
  haloSegment: { position: 'absolute', width: 6, height: 18, borderRadius: 3 },
  haloCenter: { position: 'absolute', width: 140, height: 140, alignItems: 'center', justifyContent: 'center' },
  rewardMark: {
    width: 104,
    height: 104,
    borderRadius: 38,
    borderWidth: 5,
    borderColor: colors.gold300,
    backgroundColor: colors.gold50,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '45deg' }],
  },
  rewardMarkCompact: { width: 32, height: 32, borderRadius: 11, borderWidth: 2 },
  rewardMarkHeart: { color: colors.brand700, fontFamily: fonts.sansBold, fontSize: 50, transform: [{ rotate: '-45deg' }] },
  rewardMarkHeartCompact: { fontSize: 15 },
  statusName: { color: colors.ink900, fontFamily: fonts.display, fontSize: 42, marginTop: -22 },
  statusChip: { borderRadius: radius.sm, backgroundColor: colors.gold300, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  statusChipText: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 14, textAlign: 'center' },
  statusCarryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.xs },
  statusCarry: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 14 },
  progressChevronOpen: { transform: [{ rotate: '180deg' }] },
  progressDropdown: { width: '100%', overflow: 'hidden' },
  progressCard: { width: '100%', borderWidth: 1, borderColor: colors.ink200, borderRadius: radius.sm, padding: spacing.md, gap: spacing.sm, backgroundColor: colors.white },
  progressHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.sm },
  progressTitleWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  progressTitle: { flex: 1, color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 13 },
  progressRemaining: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 12 },
  progressTrack: { height: 7, borderRadius: radius.pill, backgroundColor: colors.ink200, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: radius.pill, backgroundColor: colors.brand700 },
  progressMilestones: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressCheck: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 22 },
  progressLock: { color: colors.brand500, fontFamily: fonts.sansBold, fontSize: 22 },
  perkRow: {
    minHeight: 82,
    borderRadius: radius.pill,
    backgroundColor: colors.brand50,
    borderBottomWidth: 1,
    borderBottomColor: colors.ink200,
    paddingHorizontal: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  perkIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: colors.gold50, alignItems: 'center', justifyContent: 'center' },
  perkIconLocked: { backgroundColor: colors.brand100 },
  perkIconText: { color: colors.brand700, fontFamily: fonts.display, fontSize: 24 },
  perkLabel: { flex: 1, color: colors.ink900, fontFamily: fonts.sans, fontSize: 16, lineHeight: 22 },
  nextTierBanner: {
    minHeight: 112,
    borderRadius: radius.md,
    backgroundColor: colors.brand200,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  crownMark: { width: 76, height: 76, borderRadius: 22, backgroundColor: colors.white, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-4deg' }] },
  crownText: { color: colors.brand700, fontFamily: fonts.display, fontSize: 52 },
  nextTierCopy: { flex: 1, gap: 4 },
  nextTierName: { color: colors.ink900, fontFamily: fonts.display, fontSize: 34 },
  nextTierThreshold: { color: colors.ink700, fontFamily: fonts.sans, fontSize: 12, lineHeight: 17 },
  earnList: { gap: spacing.sm },
  earnRow: {
    minHeight: 80,
    borderRadius: radius.pill,
    backgroundColor: colors.brand50,
    borderWidth: 1,
    borderColor: colors.brand100,
    paddingHorizontal: spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  earnRowComplete: { opacity: 0.42 },
  earnLabel: { flex: 1, color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 17 },
  earnLabelComplete: { textDecorationLine: 'line-through', color: colors.ink500 },
  earnValue: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 14, backgroundColor: colors.brand200, paddingHorizontal: 12, paddingVertical: 10, borderRadius: radius.sm },
  earnValueComplete: { backgroundColor: colors.brand100, color: colors.ink500 },
  explainerCard: { marginTop: spacing.sm, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.gold50, gap: spacing.sm },
  explainerTitle: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 18 },
  explainerBody: { color: colors.ink700, fontFamily: fonts.sans, fontSize: 14, lineHeight: 21 },
  cashCard: { minHeight: 230, borderRadius: radius.md, overflow: 'hidden', padding: spacing.lg, ...shadow.card },
  cashCardPressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  cashHint: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 14 },
  cashBalance: { position: 'absolute', top: spacing.lg, right: spacing.lg, color: colors.ink900, fontFamily: fonts.display, fontSize: 34 },
  cashBottom: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  cashBrand: { color: colors.ink900, fontFamily: fonts.display, fontSize: 33 },
  cashSubbrand: { color: colors.ink700, fontFamily: fonts.sansBold, fontSize: 10, letterSpacing: 1.5 },
  currencyPill: { borderRadius: radius.pill, backgroundColor: 'rgba(125,90,60,0.12)', paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  currencyText: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 14 },
  actionRow: { minHeight: 82, borderRadius: radius.pill, backgroundColor: colors.brand50, borderWidth: 1, borderColor: colors.ink200, paddingHorizontal: spacing.lg, flexDirection: 'row', alignItems: 'center', gap: spacing.md },
  actionRowLabel: { flex: 1, color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 17 },
  cashActivity: { borderTopWidth: 1, borderTopColor: colors.ink200 },
  activityRow: { minHeight: 86, borderBottomWidth: 1, borderBottomColor: colors.ink200, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  activityCopy: { flex: 1, gap: 4 },
  activityTitle: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 16 },
  activityDate: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 13 },
  activityAmount: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 15 },
  activityAmountPositive: { borderRadius: radius.sm, backgroundColor: colors.brand100, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  emptyActivity: { paddingVertical: spacing.xl, alignItems: 'center', gap: spacing.xs },
  emptyActivityTitle: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 17 },
  emptyActivityBody: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 13 },
  perkSheet: { minHeight: '62%', maxHeight: '90%', borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.white, padding: spacing.lg, gap: spacing.md },
  helpSheet: { borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.white, padding: spacing.lg, gap: spacing.md, height: '88%', maxHeight: '88%', justifyContent: 'space-between' },
  helpScroll: { flex: 1 },
  helpScrollContent: { gap: spacing.md, paddingBottom: spacing.xs },
  helpDoneButton: { minHeight: 56, borderRadius: radius.pill, backgroundColor: colors.ink900, alignItems: 'center', justifyContent: 'center' },
  helpDoneText: { color: colors.white, fontFamily: fonts.sansBold, fontSize: 18 },
  referralSheet: { flex: 1, marginTop: 78, borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.white, padding: spacing.md, gap: spacing.lg },
  sheetTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.md },
  sheetBadges: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  sheetTierBadge: { borderRadius: radius.sm, backgroundColor: colors.brand200, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm },
  sheetTierText: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 14 },
  lockedBadge: { flexDirection: 'row', alignItems: 'center', gap: spacing.xs },
  lockedBadgeText: { color: colors.ink400, fontFamily: fonts.sansBold, fontSize: 14 },
  closeButton: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.brand50, alignItems: 'center', justifyContent: 'center' },
  sheetTitle: { color: colors.ink900, fontFamily: fonts.display, fontSize: 38, lineHeight: 44 },
  sheetBody: { color: colors.ink700, fontFamily: fonts.sans, fontSize: 16, lineHeight: 24 },
  sheetSpacer: { flex: 1 },
  referralPointsBadge: { borderRadius: radius.sm, backgroundColor: colors.brand200, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm },
  referralPointsText: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 14 },
  referralTitle: { color: colors.ink900, fontFamily: fonts.display, fontSize: 42, lineHeight: 48 },
  referralBody: { color: colors.ink700, fontFamily: fonts.sans, fontSize: 16, lineHeight: 24 },
  referralLinkCard: { minHeight: 72, borderRadius: radius.md, borderWidth: 1, borderColor: colors.ink200, backgroundColor: colors.white, padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  referralLink: { flex: 1, borderRadius: radius.pill, backgroundColor: colors.brand50, color: colors.ink500, fontFamily: fonts.sans, fontSize: 15, padding: spacing.sm },
  referralFootnote: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 12, lineHeight: 18 },
  referralDivider: { height: 1, backgroundColor: colors.ink200 },
  referralPendingTitle: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 24 },
  referralEmpty: { minHeight: 66, borderRadius: radius.md, borderWidth: 1, borderColor: colors.ink200, alignItems: 'center', justifyContent: 'center' },
  referralEmptyText: { color: colors.ink700, fontFamily: fonts.sans, fontSize: 16 },
  pendingReferral: { minHeight: 62, borderRadius: radius.md, backgroundColor: colors.brand50, paddingHorizontal: spacing.md, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pendingReferralCode: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 14 },
  pendingReferralStatus: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 13, textTransform: 'capitalize' },
  helpRule: { borderTopWidth: 1, borderTopColor: colors.ink200, paddingTop: spacing.md, gap: 3 },
  helpRuleTitle: { color: colors.ink900, fontFamily: fonts.sansBold, fontSize: 16 },
  helpRuleBody: { color: colors.ink500, fontFamily: fonts.sans, fontSize: 14, lineHeight: 20 },
  pressed: { opacity: 0.66 },
  rowPressed: { opacity: 0.76, transform: [{ scale: 0.99 }] },
});
