import { StyleSheet } from 'react-native';
import { useTokens as useBrandTokens, type BrandTokens } from '@platform/ui';


/**
 * Every style for the Rewards tab and its sheets.
 *
 * Kept as one sheet rather than split alongside the components: the tabs, rows
 * and sheets share a great many of these, and partitioning them would either
 * duplicate values or leave a "shared" file that is most of the sheet anyway.
 * One source keeps the tab surfaces visually identical by construction.
 */
export const createStyles = (tokens: BrandTokens) => StyleSheet.create({
  safeTop: { flex: 1, backgroundColor: tokens.surface },
  screen: { backgroundColor: tokens.surface },
  screenContent: { paddingTop: 0, paddingHorizontal: 0, paddingBottom: 138, gap: 0 },
  stickyNav: { backgroundColor: tokens.surface, zIndex: 3, elevation: 3 },
  whiteBody: { backgroundColor: tokens.surface, minHeight: 780 },
  demoTierBar: { paddingHorizontal: 0 },
  demoTierRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 4 },
  demoTierItem: { flex: 1, minWidth: 0, alignItems: 'center', gap: 4 },
  demoTierChip: {
    width: '100%',
    minHeight: 42,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    borderWidth: 2,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 2,
  },
  demoTierChipSelected: { borderWidth: 3 },
  demoTierChipLocked: { backgroundColor: tokens.secondary, borderColor: tokens.textMuted },
  demoTierChipContent: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 3 },
  demoTierText: { fontFamily: tokens.fontBody, fontSize: 13, textAlign: 'center' },
  demoTierPercent: { fontFamily: tokens.fontBody, fontSize: 10, lineHeight: 13 },
  demoTierArrow: { flexShrink: 0, marginTop: 15 },
  tabContent: { paddingHorizontal: tokens.spacing.lg, paddingTop: tokens.spacing.lg, gap: tokens.spacing.lg },
  tabContentCompact: { paddingHorizontal: tokens.spacing.md, paddingTop: tokens.spacing.md, gap: tokens.spacing.md },
  header: {
    minHeight: 44,
    paddingHorizontal: tokens.spacing.lg,
    paddingBottom: tokens.spacing.md,
    backgroundColor: tokens.surface,
    zIndex: 3,
    elevation: 3,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerCompact: { paddingHorizontal: tokens.spacing.md },
  headerTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 22 },
  headerTitleCompact: { fontSize: 19 },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  headerActionsCompact: { gap: tokens.spacing.sm },
  tierChip: {
    minHeight: 34,
    borderRadius: tokens.radius.pill,
    backgroundColor: 'rgba(110,75,122,0.11)',
    paddingLeft: tokens.spacing.md,
    paddingRight: tokens.spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.sm,
  },
  tierChipCompact: { minHeight: 30 },
  tierChipText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  tierChipTextCompact: { fontSize: 13 },
  helpButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(110,75,122,0.11)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  helpButtonCompact: { width: 32, height: 32, borderRadius: 16 },
  helpText: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: tokens.textMuted,
    color: tokens.textMuted,
    fontFamily: tokens.fontBody,
    fontSize: 14,
    lineHeight: 19,
    textAlign: 'center',
  },
  tabs: {
    height: 48,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: tokens.spacing.xl,
    paddingHorizontal: tokens.spacing.lg,
    backgroundColor: tokens.surfaceElevated,
    borderBottomWidth: 1,
    borderBottomColor: tokens.secondary,
    zIndex: 2,
    elevation: 2,
  },
  tab: { alignItems: 'center', justifyContent: 'flex-end', gap: 8 },
  tabLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  tabLabelCompact: { fontSize: 13 },
  tabLabelActive: { fontFamily: tokens.fontBody },
  tabIndicator: { alignSelf: 'stretch', height: 3, borderRadius: tokens.radius.pill, backgroundColor: tokens.textPrimary },
  pointsHero: {
    minHeight: 210,
    borderRadius: tokens.radius.lg,
    overflow: 'hidden',
    padding: tokens.spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pointsCopy: { zIndex: 2, flex: 1, gap: tokens.spacing.sm },
  pointsLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 18 },
  pointsNumber: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 58, lineHeight: 66 },
  earnRatePill: {
    alignSelf: 'flex-start',
    minHeight: 36,
    borderRadius: tokens.radius.md,
    backgroundColor: 'rgba(255,255,255,0.48)',
    paddingHorizontal: tokens.spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.sm,
  },
  earnRateText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 12 },
  sectionTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 25, marginTop: tokens.spacing.lg },
  rewardList: { gap: 2 },
  rewardRow: {
    minHeight: 112,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    borderBottomWidth: 1,
    borderBottomColor: tokens.secondary,
    paddingHorizontal: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
  },
  rewardRowLocked: { opacity: 0.56 },
  rewardHeart: {
    width: 66,
    height: 66,
    borderRadius: 33,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardCopy: { flex: 1, gap: 4 },
  rewardTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 18 },
  rewardCost: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 15 },
  lockedText: { color: tokens.textMuted },
  footnote: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 18, paddingVertical: tokens.spacing.lg },
  statusHero: { alignItems: 'center', gap: tokens.spacing.md },
  haloSegment: { position: 'absolute', width: 6, height: 18, borderRadius: 3 },
  haloCenter: { position: 'absolute', width: 140, height: 140, alignItems: 'center', justifyContent: 'center' },
  rewardMark: {
    width: 104,
    height: 104,
    borderRadius: 38,
    borderWidth: 5,
    borderColor: tokens.accent,
    backgroundColor: tokens.surface,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ rotate: '45deg' }],
  },
  rewardMarkCompact: { width: 32, height: 32, borderRadius: 11, borderWidth: 2 },
  rewardMarkHeart: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 50, transform: [{ rotate: '-45deg' }] },
  rewardMarkHeartCompact: { fontSize: 15 },
  statusName: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 42, marginTop: -22 },
  statusChip: { borderRadius: tokens.radius.md, backgroundColor: tokens.accent, paddingHorizontal: tokens.spacing.lg, paddingVertical: tokens.spacing.md },
  statusChipText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14, textAlign: 'center' },
  statusCarryRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: tokens.spacing.sm },
  statusCarry: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  progressChevronOpen: { transform: [{ rotate: '180deg' }] },
  progressDropdown: { width: '100%', overflow: 'hidden' },
  progressCard: { width: '100%', borderWidth: 1, borderColor: tokens.secondary, borderRadius: tokens.radius.md, padding: tokens.spacing.lg, gap: tokens.spacing.md, backgroundColor: tokens.surfaceElevated },
  progressHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.md },
  progressTitleWrap: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  progressTitle: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 13 },
  progressRemaining: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12 },
  progressTrack: { height: 7, borderRadius: tokens.radius.pill, backgroundColor: tokens.secondary, overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: tokens.radius.pill, backgroundColor: tokens.primary },
  progressMilestones: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressCheck: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 22 },
  progressLock: { color: tokens.secondary, fontFamily: tokens.fontBody, fontSize: 22 },
  perkRow: {
    minHeight: 82,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    borderBottomWidth: 1,
    borderBottomColor: tokens.secondary,
    paddingHorizontal: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
  },
  perkIcon: { width: 40, height: 40, borderRadius: 20, backgroundColor: tokens.surface, alignItems: 'center', justifyContent: 'center' },
  perkIconLocked: { backgroundColor: tokens.surface },
  perkIconText: { color: tokens.primary, fontFamily: tokens.fontDisplay, fontSize: 24 },
  perkLabel: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16, lineHeight: 22 },
  nextTierBanner: {
    minHeight: 112,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surface,
    padding: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
  },
  crownMark: { width: 76, height: 76, borderRadius: 22, backgroundColor: tokens.surfaceElevated, alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '-4deg' }] },
  crownText: { color: tokens.primary, fontFamily: tokens.fontDisplay, fontSize: 52 },
  nextTierCopy: { flex: 1, gap: 4 },
  nextTierName: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 34 },
  nextTierThreshold: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 17 },
  earnList: { gap: tokens.spacing.md },
  earnRow: {
    minHeight: 80,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.surface,
    paddingHorizontal: tokens.spacing.xl,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: tokens.spacing.lg,
  },
  earnRowComplete: { opacity: 0.42 },
  earnLabel: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 17 },
  earnLabelComplete: { textDecorationLine: 'line-through', color: tokens.textMuted },
  earnValue: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14, backgroundColor: tokens.surface, paddingHorizontal: 12, paddingVertical: 10, borderRadius: tokens.radius.md },
  earnValueComplete: { backgroundColor: tokens.surface, color: tokens.textMuted },
  explainerCard: { marginTop: tokens.spacing.md, padding: tokens.spacing.xl, borderRadius: tokens.radius.lg, backgroundColor: tokens.surface, gap: tokens.spacing.md },
  explainerTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 18 },
  explainerBody: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14, lineHeight: 21 },
  cashCard: { minHeight: 230, borderRadius: tokens.radius.lg, overflow: 'hidden', padding: tokens.spacing.xl, shadowColor: tokens.textPrimary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: tokens.elevation.card, shadowRadius: 24, elevation: 5 },
  cashCardPressed: { opacity: 0.82, transform: [{ scale: 0.99 }] },
  cashHint: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  cashBalance: { position: 'absolute', top: tokens.spacing.xl, right: tokens.spacing.xl, color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 34 },
  cashBottom: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  cashBrand: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 33 },
  cashSubbrand: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 10, letterSpacing: 1.5 },
  currencyPill: { borderRadius: tokens.radius.pill, backgroundColor: 'rgba(125,90,60,0.12)', paddingHorizontal: tokens.spacing.lg, paddingVertical: tokens.spacing.md },
  currencyText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  actionRow: { minHeight: 82, borderRadius: tokens.radius.pill, backgroundColor: tokens.surface, borderWidth: 1, borderColor: tokens.secondary, paddingHorizontal: tokens.spacing.xl, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.lg },
  actionRowLabel: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 17 },
  cashActivity: { borderTopWidth: 1, borderTopColor: tokens.secondary },
  activityRow: { minHeight: 86, borderBottomWidth: 1, borderBottomColor: tokens.secondary, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.lg },
  activityCopy: { flex: 1, gap: 4 },
  activityTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  activityDate: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
  activityAmount: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  activityAmountPositive: { borderRadius: tokens.radius.md, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.md, paddingVertical: tokens.spacing.sm },
  emptyActivity: { paddingVertical: tokens.spacing.xxl, alignItems: 'center', gap: tokens.spacing.sm },
  emptyActivityTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 17 },
  emptyActivityBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
  perkSheet: { minHeight: '62%', maxHeight: '90%', borderTopLeftRadius: tokens.radius.lg, borderTopRightRadius: tokens.radius.lg, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.xl, gap: tokens.spacing.lg },
  helpSheet: { borderTopLeftRadius: tokens.radius.lg, borderTopRightRadius: tokens.radius.lg, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.xl, gap: tokens.spacing.lg, height: '88%', maxHeight: '88%', justifyContent: 'space-between' },
  helpScroll: { flex: 1 },
  helpScrollContent: { gap: tokens.spacing.lg, paddingBottom: tokens.spacing.sm },
  helpDoneButton: { minHeight: 56, borderRadius: tokens.radius.pill, backgroundColor: tokens.textPrimary, alignItems: 'center', justifyContent: 'center' },
  helpDoneText: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 18 },
  referralSheet: { flex: 1, marginTop: 78, borderTopLeftRadius: tokens.radius.lg, borderTopRightRadius: tokens.radius.lg, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.lg, gap: tokens.spacing.xl },
  sheetTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.lg },
  sheetBadges: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  sheetTierBadge: { borderRadius: tokens.radius.md, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.md, paddingVertical: tokens.spacing.md },
  sheetTierText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  lockedBadge: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.sm },
  lockedBadgeText: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  closeButton: { width: 48, height: 48, borderRadius: 24, backgroundColor: tokens.surface, alignItems: 'center', justifyContent: 'center' },
  sheetTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 38, lineHeight: 44 },
  sheetBody: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16, lineHeight: 24 },
  sheetSpacer: { flex: 1 },
  referralPointsBadge: { borderRadius: tokens.radius.md, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.md, paddingVertical: tokens.spacing.md },
  referralPointsText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  referralTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 42, lineHeight: 48 },
  referralBody: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16, lineHeight: 24 },
  referralLinkCard: { minHeight: 72, borderRadius: tokens.radius.lg, borderWidth: 1, borderColor: tokens.secondary, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.lg, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  referralLink: { flex: 1, borderRadius: tokens.radius.pill, backgroundColor: tokens.surface, color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 15, padding: tokens.spacing.md },
  referralFootnote: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 18 },
  referralDivider: { height: 1, backgroundColor: tokens.secondary },
  referralPendingTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 24 },
  referralEmpty: { minHeight: 66, borderRadius: tokens.radius.lg, borderWidth: 1, borderColor: tokens.secondary, alignItems: 'center', justifyContent: 'center' },
  referralEmptyText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  pendingReferral: { minHeight: 62, borderRadius: tokens.radius.lg, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.lg, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  pendingReferralCode: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  pendingReferralStatus: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13, textTransform: 'capitalize' },
  helpRule: { borderTopWidth: 1, borderTopColor: tokens.secondary, paddingTop: tokens.spacing.lg, gap: 3 },
  helpRuleTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  helpRuleBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14, lineHeight: 20 },
  pressed: { opacity: 0.66 },
  rowPressed: { opacity: 0.76, transform: [{ scale: 0.99 }] },
});

export function useRewardStyles() { return createStyles(useBrandTokens()); }
