/**
 * The product cut-outs this build ships, for this tenant.
 *
 * GENERATED by `pnpm onboard --tenant <slug> --apply` from
 * `tenants/<slug>/assets/products/`. Checked in for the same reason
 * `brand.json` is: Metro cannot require a path chosen at runtime, so
 * onboarding materialises the choice. Editing this by hand puts it out of step
 * with the tenant folder.
 *
 * A slug missing from this map is not an error. `resolveProductMedia` returns
 * null and the shelf is one row shorter -- a tenant part-way through shooting
 * its menu still boots, which is the one place this path deliberately differs
 * from the menu photographs.
 */
import { EMPTY_PRODUCT_MEDIA, type ProductMediaCatalog } from '@platform/domain';

import adeniChai from '../../assets/products/adeni-chai.webp';
import chaiLatte from '../../assets/products/chai-latte.webp';
import honeyLavenderMatcha from '../../assets/products/honey-lavender-matcha.webp';
import londonFog from '../../assets/products/london-fog.webp';
import looseLeafTea from '../../assets/products/loose-leaf-tea.webp';
import matchaLatte from '../../assets/products/matcha-latte.webp';
import orangeBlossomMatcha from '../../assets/products/orange-blossom-matcha.webp';
import spanishMatcha from '../../assets/products/spanish-matcha.webp';
import strawberryMatcha from '../../assets/products/strawberry-matcha.webp';
import ubeMatcha from '../../assets/products/ube-matcha.webp';

/** slug -> Metro module id. The one place a cut-out asset is named. */
export const BUNDLED_CUTOUTS: Readonly<Record<string, number>> = {
  'adeni-chai': adeniChai,
  'chai-latte': chaiLatte,
  'honey-lavender-matcha': honeyLavenderMatcha,
  'london-fog': londonFog,
  'loose-leaf-tea': looseLeafTea,
  'matcha-latte': matchaLatte,
  'orange-blossom-matcha': orangeBlossomMatcha,
  'spanish-matcha': spanishMatcha,
  'strawberry-matcha': strawberryMatcha,
  'ube-matcha': ubeMatcha,
};

/**
 * The catalog the resolver reads.
 *
 * `remote` stays empty until `menu_items.image_url` has a writer. Nothing
 * about this file or its callers changes when it does -- that is the whole
 * reason the resolver returns a reference rather than a module id.
 */
export const TENANT_PRODUCT_MEDIA: ProductMediaCatalog = {
  bundled: new Set(Object.keys(BUNDLED_CUTOUTS)),
  remote: EMPTY_PRODUCT_MEDIA.remote,
};
