import { StyleSheet } from 'react-native';

import { alpha, type BrandTokens } from '@platform/ui';

export const createBottomNavStyles = (tokens: BrandTokens) => StyleSheet.create({
  quickAction: {
    width: 56,
    height: 56,
    borderRadius: 28,
    marginHorizontal: 2,
    backgroundColor: tokens.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionPressed: { opacity: 0.85 },
  wrap: {
    position: 'absolute',
    left: 15,
    right: 15,
    height: 64,
    borderRadius: tokens.radius.pill,
    overflow: 'hidden',
    shadowColor: tokens.textPrimary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: tokens.elevation.card,
    shadowRadius: 24,
    elevation: 5,
  },
  surface: { borderRadius: tokens.radius.pill },
  content: { flex: 1, padding: 4, flexDirection: 'row' },
  webGlassFallback: {
    backgroundColor: alpha(tokens.surfaceElevated, 0.82),
    borderWidth: 1,
    borderColor: tokens.secondary,
  },
  item: {
    flex: 1,
    borderRadius: tokens.radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  itemFill: { borderRadius: tokens.radius.pill },
  itemFillSelected: { borderWidth: 1, borderColor: tokens.surface },
  webSelectedFallback: { backgroundColor: tokens.surface },
  iconWrap: {
    width: 28,
    height: 25,
    borderRadius: tokens.radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badge: {
    position: 'absolute',
    top: -5,
    right: -7,
    minWidth: 16,
    height: 16,
    paddingHorizontal: 3,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.danger,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeText: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 10 },
  label: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 10 },
  labelSelected: { fontFamily: tokens.fontBody },
  pressed: { opacity: 0.68 },
  staffWrap: {
    backgroundColor: tokens.surfaceElevated,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: tokens.secondary,
  },
  staffContent: { height: 58, flexDirection: 'row', paddingHorizontal: 4 },
  staffItem: { minHeight: 52, minWidth: 44, borderRadius: tokens.radius.sm },
  staffLabel: { color: tokens.textMuted, fontSize: 11 },
});
