/** GENERATED by `pnpm onboard --tenant juniper-base-demo --apply`. */
import menuPlanningSession from '../../../assets/menu/juniper-base-demo/planning-session.webp';
import menuTeamWorkshop from '../../../assets/menu/juniper-base-demo/team-workshop.webp';
import menuStarterGuide from '../../../assets/menu/juniper-base-demo/starter-guide.webp';
import menuSupportPlan from '../../../assets/menu/juniper-base-demo/support-plan.webp';

export const TENANT_MENU_MEDIA: Readonly<Record<string, number>> = {
  'planning-session': menuPlanningSession,
  'team-workshop': menuTeamWorkshop,
  'starter-guide': menuStarterGuide,
  'support-plan': menuSupportPlan,
};
