/** GENERATED by `pnpm onboard --tenant stillpoint-builders --apply`. */
import menuProjectConsultation from '../../../assets/menu/stillpoint-builders/project-consultation.webp';
import menuPreconstructionPlan from '../../../assets/menu/stillpoint-builders/preconstruction-plan.webp';
import menuKitchenRenovation from '../../../assets/menu/stillpoint-builders/kitchen-renovation.webp';
import menuBathroomRenovation from '../../../assets/menu/stillpoint-builders/bathroom-renovation.webp';
import menuWarrantyServiceVisit from '../../../assets/menu/stillpoint-builders/warranty-service-visit.webp';

export const TENANT_MENU_MEDIA: Readonly<Record<string, number>> = {
  'project-consultation': menuProjectConsultation,
  'preconstruction-plan': menuPreconstructionPlan,
  'kitchen-renovation': menuKitchenRenovation,
  'bathroom-renovation': menuBathroomRenovation,
  'warranty-service-visit': menuWarrantyServiceVisit,
};
