/**
 * The product cut-outs this tenant has seated.
 *
 * GENERATED by `pnpm onboard --tenant stillpoint-builders --apply` from
 * `tenants/stillpoint-builders/assets/products/`.
 *
 * A menu slug missing from this map is not an error: `resolveProductMedia`
 * returns null and the shelf is one row shorter, so a tenant part-way through
 * shooting its menu still boots.
 */

/** menu slug -> Metro module id. The one place a cut-out asset is named. */
export const BUNDLED_CUTOUTS: Readonly<Record<string, number>> = {
};
