import { StyleSheet } from 'react-native';
import type { BrandTokens } from '@platform/ui';
export const createGiftStyles = (tokens: BrandTokens) => StyleSheet.create({
  checkoutShell: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, zIndex: 80, backgroundColor: tokens.surface },
  galleryContent: { paddingTop: 0, paddingHorizontal: 0, gap: tokens.spacing.xl },
  pressed: { opacity: 0.85 },
  pageTitle: {
    color: tokens.textPrimary,
    fontFamily: tokens.fontDisplay,
    fontSize: 34,
    lineHeight: 38,
    letterSpacing: -1,
  },
  infoButton: {
    width: 40,
    height: 40,
    borderRadius: tokens.radius.pill,
    borderWidth: 1,
    borderColor: tokens.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wallet: {
    marginHorizontal: tokens.spacing.xl,
    minHeight: 116,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surface,
    paddingLeft: tokens.spacing.lg,
    paddingRight: tokens.spacing.md,
    paddingVertical: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.md,
    overflow: 'hidden',
  },
  walletCompact: { marginHorizontal: tokens.spacing.lg, minHeight: 108, paddingLeft: 14, paddingRight: tokens.spacing.sm, gap: tokens.spacing.sm },
  walletCopy: { flex: 1, minWidth: 0, gap: tokens.spacing.sm },
  walletTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 21, letterSpacing: -0.4 },
  walletBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14, lineHeight: 19 },
  stack: { width: 116, height: 92 },
  stackCompact: { width: 92, height: 78 },
  stackCard: {
    position: 'absolute',
    width: 78,
    height: 52,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: tokens.surfaceElevated,
    overflow: 'hidden',
    backgroundColor: tokens.surface,
  },
  stackCardCompact: { width: 64, height: 43 },
  stackBack: { top: 0, right: 4, transform: [{ rotate: '-12deg' }] },
  stackMiddle: { top: 18, right: 26, transform: [{ rotate: '6deg' }] },
  stackFront: { top: 36, right: 2, transform: [{ rotate: '-4deg' }] },
  // Sized rather than absolutely inset: expo-image renders its <img> inside its
  // own statically-positioned wrapper on web, so `StyleSheet.absoluteFill` on
  // the Image escapes to a distant ancestor and the artwork never appears.
  fillImage: { width: '100%', height: '100%' },
  shelf: { gap: tokens.spacing.md },
  shelfTitle: {
    paddingHorizontal: tokens.spacing.xl,
    color: tokens.textPrimary,
    fontFamily: tokens.fontDisplay,
    fontSize: 23,
    letterSpacing: -0.5,
  },
  shelfRow: { paddingHorizontal: tokens.spacing.xl, gap: tokens.spacing.md },
  shelfInsetCompact: { paddingHorizontal: tokens.spacing.lg },
  shelfCard: {
    borderRadius: tokens.radius.lg,
    overflow: 'hidden',
    backgroundColor: tokens.surface,
    shadowColor: tokens.textPrimary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: tokens.elevation.card, shadowRadius: 24, elevation: 5,
  },
  sheetContent: { paddingHorizontal: tokens.spacing.xl, gap: tokens.spacing.lg, paddingBottom: 140 },
  sheetHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: tokens.spacing.lg },
  infoTitleGroup: { flex: 1, gap: tokens.spacing.sm },
  sheetTitle: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 26, letterSpacing: -0.6 },
  closeButton: { width: 42, height: 42, borderRadius: tokens.radius.pill, backgroundColor: tokens.surface, alignItems: 'center', justifyContent: 'center' },
  sheetHero: { width: '100%', aspectRatio: 3 / 2, borderRadius: tokens.radius.lg, backgroundColor: tokens.surface },
  sheetHeading: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 27, letterSpacing: -0.6 },
  sheetBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 15, lineHeight: 21 },
  selectRow: { flexDirection: 'row', gap: tokens.spacing.lg },
  selectGroup: { flex: 1, gap: tokens.spacing.sm },
  selectLabel: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  select: {
    minHeight: 56,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    paddingHorizontal: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  selectValue: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 19 },
  divider: { height: 1, backgroundColor: tokens.surface, marginVertical: tokens.spacing.md },
  sheetSection: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 21, letterSpacing: -0.4 },
  payMethod: {
    minHeight: 68,
    borderRadius: tokens.radius.lg,
    borderWidth: 1,
    borderColor: tokens.surface,
    paddingHorizontal: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.md,
  },
  payCopy: { flex: 1, gap: 2 },
  payBadge: { width: 52, height: 34, borderRadius: 8, borderWidth: 1, borderColor: tokens.textPrimary, alignItems: 'center', justifyContent: 'center' },
  payName: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  payMeta: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12 },
  defaultChip: {
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 5,
  },
  defaultChipText: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 13 },
  totalRow: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md, marginTop: tokens.spacing.md },
  totalLabel: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 22, letterSpacing: -0.4 },
  totalLeader: {
    flex: 1,
    height: 1,
    borderBottomWidth: 1,
    borderStyle: 'dashed',
    borderColor: tokens.surface,
  },
  totalValue: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 21 },
  earnBanner: {
    minHeight: 58,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surface,
    paddingHorizontal: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.md,
  },
  earnText: { flex: 1, color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 15 },
  checkoutFooter: {
    position: 'absolute',
    left: tokens.spacing.xl,
    right: tokens.spacing.xl,
    bottom: tokens.spacing.xl,
  },
  applePayButton: {
    minHeight: 56,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: tokens.spacing.xl,
  },
  applePayText: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 17 },
  payButtonBusy: { opacity: 0.7 },
  finePrint: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13, lineHeight: 18 },
  chipHeading: {
    alignSelf: 'flex-start',
    borderRadius: tokens.radius.md,
    backgroundColor: tokens.surface,
    paddingHorizontal: tokens.spacing.md,
    paddingVertical: 6,
    marginTop: tokens.spacing.md,
  },
  chipHeadingText: { color: tokens.primary, fontFamily: tokens.fontDisplay, fontSize: 20, letterSpacing: -0.3 },
  step: { flexDirection: 'row', gap: tokens.spacing.lg, alignItems: 'flex-start' },
  stepCopy: { flex: 1, gap: 2 },
  stepTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 17 },
  stepBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 15, lineHeight: 21 },
  faq: {
    borderRadius: tokens.radius.lg,
    borderWidth: 1,
    borderColor: tokens.surface,
    padding: tokens.spacing.lg,
    gap: tokens.spacing.md,
  },
  faqRow: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  faqBadge: {
    width: 26,
    height: 26,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  faqBadgeText: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 14 },
  faqQuestion: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16, lineHeight: 21 },
  faqAnswer: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 15, lineHeight: 21 },
});
