import {
  StyleSheet
} from 'react-native';

import { alpha, type BrandTokens } from '@platform/ui';


export const createBoardSheetStyles = (tokens: BrandTokens) => StyleSheet.create({
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: alpha(tokens.primary, 0.45),
  },
  sheet: {
    position: 'absolute',
    zIndex: 1,
    left: tokens.spacing.xl,
    right: tokens.spacing.xl,
    top: '12%',
    maxHeight: '76%',
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surface,
    padding: tokens.spacing.xl,
    gap: tokens.spacing.lg,
    shadowColor: tokens.textPrimary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: tokens.elevation.card, shadowRadius: 24, elevation: 5,
  },
  sheetTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 20 },
  sheetBody: { gap: tokens.spacing.md },
  sheetSection: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12, letterSpacing: 0.6, textTransform: 'uppercase', paddingTop: tokens.spacing.md },

  detailLine: { gap: 2 },
  detailLineName: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  detailLineOptions: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
  detailTotalRow: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: tokens.secondary, paddingTop: tokens.spacing.md },
  detailTotalLabel: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  detailTotalValue: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  detailPrimary: {
    minHeight: 52,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.textPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailPrimaryText: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 16 },
  detailDangerRow: { flexDirection: 'row', gap: tokens.spacing.md, flexWrap: 'wrap' },
  detailQuiet: {
    minHeight: 44,
    borderRadius: tokens.radius.pill,
    borderWidth: 1,
    borderColor: tokens.secondary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: tokens.spacing.xl,
    backgroundColor: tokens.surfaceElevated,
  },
  detailQuietText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 14 },
  detailDanger: {
    minHeight: 44,
    borderRadius: tokens.radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: tokens.spacing.xl,
    backgroundColor: tokens.danger,
  },
  detailDangerText: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 14 },
  detailStatusRow: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md },
  detailStatusText: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  detailErrorBox: { gap: tokens.spacing.md, borderWidth: 1, borderColor: tokens.danger, borderRadius: tokens.radius.lg, padding: tokens.spacing.lg },
  detailErrorText: { color: tokens.danger, fontFamily: tokens.fontBody, fontSize: 14, lineHeight: 20 },
  refundBox: { gap: tokens.spacing.md },
  refundHint: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13, lineHeight: 18 },
  refundInput: {
    borderWidth: 1,
    borderColor: tokens.secondary,
    borderRadius: tokens.radius.lg,
    paddingHorizontal: tokens.spacing.lg,
    paddingVertical: tokens.spacing.md,
    color: tokens.textPrimary,
    fontFamily: tokens.fontBody,
    fontSize: 18,
    backgroundColor: tokens.surfaceElevated,
  },

  statRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: tokens.spacing.sm },
  statLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  statValue: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },

  settingRow: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.lg, paddingVertical: tokens.spacing.md },
  settingCopy: { flex: 1, gap: 2 },
  settingLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  settingDetail: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
  switch: {
    width: 52,
    height: 32,
    borderRadius: 16,
    backgroundColor: tokens.secondary,
    padding: 3,
    justifyContent: 'center',
  },
  switchOn: { backgroundColor: tokens.success },
  switchKnob: { width: 26, height: 26, borderRadius: 13, backgroundColor: tokens.surfaceElevated },
  switchKnobOn: { alignSelf: 'flex-end' },

  eightySixRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: tokens.spacing.md },
  eightySixName: { color: tokens.textMuted, textDecorationLine: 'line-through' },
  eightySixTag: { color: tokens.danger, fontFamily: tokens.fontBody, fontSize: 13 },
  locationRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: tokens.spacing.lg },
  locationName: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  locationCurrent: { color: tokens.success, fontFamily: tokens.fontBody, fontSize: 13 },

  pinScreen: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: tokens.spacing.lg, padding: tokens.spacing.xxl, backgroundColor: tokens.surface },
  pinTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 26 },
  pinHint: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14, textAlign: 'center' },
  pinInput: {
    minWidth: 180,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: tokens.secondary,
    borderRadius: tokens.radius.lg,
    paddingHorizontal: tokens.spacing.lg,
    paddingVertical: tokens.spacing.lg,
    color: tokens.textPrimary,
    fontFamily: tokens.fontBody,
    fontSize: 24,
    letterSpacing: 8,
    backgroundColor: tokens.surfaceElevated,
  },
});
