import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: { ...StyleSheet.absoluteFillObject, zIndex: 20, flexDirection: 'row', justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject },
  backdropPress: { flex: 1 },
  drawer: {
    width: 480, maxWidth: '88%', height: '100%', padding: 28,
    shadowRadius: 24, shadowOffset: { width: -8, height: 0 }, elevation: 16,
  },
  drawerContents: { flex: 1, gap: 18 },
  heading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 },
  headingCopy: { flex: 1, gap: 2 },
  title: {},
  countText: {},
  close: { minWidth: 84, minHeight: 60, paddingHorizontal: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 2 },
  closeLabel: { fontWeight: '700' },
  empty: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 24 },
  emptyText: {},
  lines: { paddingBottom: 18 },
  line: { flexDirection: 'row', alignItems: 'flex-start', gap: 14, paddingVertical: 18, borderBottomWidth: 1 },
  lineBody: { flex: 1, gap: 12 },
  lineTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  lineCopy: { flex: 1, gap: 3 },
  lineName: { fontWeight: '700' },
  lineMeta: {},
  linePrice: { fontWeight: '700', textAlign: 'right' },
  summary: { borderTopWidth: 1, paddingTop: 16, gap: 10 },
  moneyRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 16 },
  moneyLabel: { flex: 1 },
  moneyAmount: { fontWeight: '600' },
  totalRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 8 },
  totalLabel: { fontWeight: '700' },
  totalAmount: { fontWeight: '700' },
});
