/**
 * Expo config, tenant-driven (rule 7: one customer binary per brand).
 *
 * `EXPO_PUBLIC_TENANT` picks which applied tenant this build is for; identity
 * -- display name, slug, scheme, bundle/package id, EAS project -- comes from
 * that tenant's applied `src/tenants/<slug>/brand.json`. Icons and splash use
 * the matching `assets/tenants/<slug>` slot generated by onboarding, so every
 * applied tenant remains buildable from the same checkout.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import type { ConfigContext, ExpoConfig } from 'expo/config';

/**
 * Which applied tenant this build is for, by the same rule the app uses at runtime.
 *
 * `src/tenants/` holds one directory per applied tenant and `applied.json`
 * names them; `src/tenants/index.ts` selects one from `EXPO_PUBLIC_TENANT` when
 * the bundle boots. This has to agree with that or the build is the exact
 * failure the slot layout exists to prevent -- one shop's identity over another
 * shop's menu, correctly signed, with nothing in the log to say so. Duplicated
 * here rather than imported because Expo's config loader transpiles this file
 * and not workspace TypeScript it imports; `src/tenant/tenant.test.ts` pins the
 * two answers together.
 *
 * `TENANT` stays accepted as the legacy build-time name, but only when it
 * agrees with `EXPO_PUBLIC_TENANT`: `TENANT` alone cannot reach the bundle, so
 * honouring it by itself is how a franchisee got a correctly named binary
 * carrying somebody else's menu.
 */
function resolveAppliedTenant(appDirectory: string, app: string): string {
  const manifest: { slugs?: string[] } = JSON.parse(
    readFileSync(join(appDirectory, 'src', 'tenants', 'applied.json'), 'utf8'),
  );
  // Shape-checked, not just membership-checked: these entries are joined into
  // a filesystem path below, and a hand-edited `..` would read out of the slot
  // directory entirely. Kebab-case cannot contain a dot or a slash.
  const slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
  const applied = [...(manifest.slugs ?? [])].filter((slug) => slugPattern.test(slug)).sort();
  const runtime = process.env.EXPO_PUBLIC_TENANT?.trim() ?? '';
  const legacy = process.env.TENANT?.trim() ?? '';
  if (legacy !== '' && legacy !== runtime) {
    throw new Error(
      `TENANT="${legacy}" cannot reach the bundle; only EXPO_PUBLIC_TENANT is inlined. `
      + `Build with EXPO_PUBLIC_TENANT=${legacy} instead.`,
    );
  }
  if (applied.length === 0) {
    throw new Error(`apps/${app} has no tenant applied. Run \`pnpm onboard --tenant <slug> --apply\`.`);
  }
  if (runtime !== '') {
    if (!slugPattern.test(runtime) || !applied.includes(runtime)) {
      throw new Error(
        `EXPO_PUBLIC_TENANT="${runtime}" is not applied to apps/${app}. Applied: ${applied.join(', ')}. `
        + `Run \`pnpm onboard --tenant ${runtime} --apply\` first.`,
      );
    }
    return runtime;
  }
  const only = applied[0];
  if (applied.length === 1 && only !== undefined) return only;
  throw new Error(
    `apps/${app} bundles ${applied.length} tenants (${applied.join(', ')}) and EXPO_PUBLIC_TENANT is not set. `
    + 'Set EXPO_PUBLIC_TENANT=<slug> so this build picks one.',
  );
}

/** Read from the applied copy, so the identity always matches the bundled menu. */
export function appliedBrandPath(appDirectory: string, app: string): string {
  return join(appDirectory, 'src', 'tenants', resolveAppliedTenant(appDirectory, app), 'brand.json');
}

type BrandFile = {
  identity: { slug: string; name: string; bundleId: string; scheme: string; easProjectId: string };
  tokens?: { primary?: string; surface?: string };
};

const brand: BrandFile = JSON.parse(readFileSync(appliedBrandPath(__dirname, 'customer'), 'utf8'));
const artworkRoot = `./assets/tenants/${brand.identity.slug}`;
// Expo SDK 54 copies EXPO_PUBLIC_FOLDER verbatim during web export. Point it
// at one validated tenant slot so a Coffee export cannot carry Stillpoint's
// install manifest/icons (and vice versa) merely because both are applied.
process.env.EXPO_PUBLIC_FOLDER = `public/tenants/${brand.identity.slug}`;

export default ({ config }: ConfigContext): ExpoConfig => ({
  ...config,
  name: brand.identity.name,
  slug: brand.identity.slug,
  version: '1.0.0',
  orientation: 'portrait',
  icon: `${artworkRoot}/images/icon.png`,
  scheme: brand.identity.scheme,
  runtimeVersion: 'exposdk:54.0.0',
  userInterfaceStyle: 'light',
  ios: {
    icon: `${artworkRoot}/expo.icon`,
    bundleIdentifier: brand.identity.bundleId,
    supportsTablet: false,
    usesAppleSignIn: false,
    infoPlist: {
      NSMotionUsageDescription: `${brand.identity.name} uses device motion to animate interactive artwork.`,
    },
    config: {
      usesNonExemptEncryption: false,
    },
  },
  android: {
    adaptiveIcon: {
      backgroundColor: brand.tokens?.primary ?? '#241710',
      foregroundImage: `${artworkRoot}/images/android-icon-foreground.png`,
      backgroundImage: `${artworkRoot}/images/android-icon-background.png`,
      monochromeImage: `${artworkRoot}/images/android-icon-monochrome.png`,
    },
    predictiveBackGestureEnabled: false,
    permissions: ['android.permission.READ_CALENDAR', 'android.permission.WRITE_CALENDAR'],
    package: brand.identity.bundleId,
  },
  web: {
    output: 'static',
    favicon: `${artworkRoot}/images/favicon.png`,
  },
  plugins: [
    'expo-router',
    [
      'expo-splash-screen',
      {
        backgroundColor: brand.tokens?.surface ?? '#FAF5EF',
        image: `${artworkRoot}/brand/logo.png`,
        imageWidth: 180,
      },
    ],
    'expo-secure-store',
    [
      'expo-image-picker',
      {
        photosPermission: `Allow ${brand.identity.name} to choose a profile photo for your account.`,
        cameraPermission: false,
        microphonePermission: false,
      },
    ],
    [
      'expo-calendar',
      {
        calendarPermission: `Allow ${brand.identity.name} to add a scheduled time to your calendar.`,
        remindersPermission: false,
      },
    ],
    'expo-video',
  ],
  experiments: {
    typedRoutes: true,
    reactCompiler: true,
  },
  extra: {
    router: {},
    ...(brand.identity.easProjectId
      ? { eas: { projectId: brand.identity.easProjectId } }
      : {}),
  },
  owner: 'tylerdevries222',
  ...(brand.identity.easProjectId
    ? { updates: { url: `https://u.expo.dev/${brand.identity.easProjectId}` } }
    : {}),
});
