/** GENERATED by `pnpm onboard --tenant coffee-story --apply`. */
import menuEspresso from '../../../assets/menu/coffee-story/espresso.webp';
import menuAmericano from '../../../assets/menu/coffee-story/americano.webp';
import menuLatte from '../../../assets/menu/coffee-story/latte.webp';
import menuCappuccino from '../../../assets/menu/coffee-story/cappuccino.webp';
import menuFlatWhite from '../../../assets/menu/coffee-story/flat-white.webp';
import menuCortado from '../../../assets/menu/coffee-story/cortado.webp';
import menuMacchiato from '../../../assets/menu/coffee-story/macchiato.webp';
import menuMocha from '../../../assets/menu/coffee-story/mocha.webp';
import menuColdBrew from '../../../assets/menu/coffee-story/cold-brew.webp';
import menuFrappe from '../../../assets/menu/coffee-story/frappe.webp';
import menuTiramisuLatte from '../../../assets/menu/coffee-story/tiramisu-latte.webp';
import menuSpanishLatte from '../../../assets/menu/coffee-story/spanish-latte.webp';
import menuPistachioLatte from '../../../assets/menu/coffee-story/pistachio-latte.webp';
import menuUbeLatte from '../../../assets/menu/coffee-story/ube-latte.webp';
import menuHoneyLavenderLatte from '../../../assets/menu/coffee-story/honey-lavender-latte.webp';
import menuHoneyRoseLatte from '../../../assets/menu/coffee-story/honey-rose-latte.webp';
import menuBrownSugarShakenEspresso from '../../../assets/menu/coffee-story/brown-sugar-shaken-espresso.webp';
import menuBiscoffLatte from '../../../assets/menu/coffee-story/biscoff-latte.webp';
import menuSpanishOatShaken from '../../../assets/menu/coffee-story/spanish-oat-shaken.webp';
import menuLibyanNescafe from '../../../assets/menu/coffee-story/libyan-nescafe.webp';
import menuTurkishCoffee from '../../../assets/menu/coffee-story/turkish-coffee.webp';
import menuLooseLeafTea from '../../../assets/menu/coffee-story/loose-leaf-tea.webp';
import menuChaiLatte from '../../../assets/menu/coffee-story/chai-latte.webp';
import menuLondonFog from '../../../assets/menu/coffee-story/london-fog.webp';
import menuMatchaLatte from '../../../assets/menu/coffee-story/matcha-latte.webp';
import menuStrawberryMatcha from '../../../assets/menu/coffee-story/strawberry-matcha.webp';
import menuUbeMatcha from '../../../assets/menu/coffee-story/ube-matcha.webp';
import menuOrangeBlossomMatcha from '../../../assets/menu/coffee-story/orange-blossom-matcha.webp';
import menuHoneyLavenderMatcha from '../../../assets/menu/coffee-story/honey-lavender-matcha.webp';
import menuSpanishMatcha from '../../../assets/menu/coffee-story/spanish-matcha.webp';
import menuAdeniChai from '../../../assets/menu/coffee-story/adeni-chai.webp';
import menuBobaMilkTea from '../../../assets/menu/coffee-story/boba-milk-tea.webp';
import menuBobaBrownSugar from '../../../assets/menu/coffee-story/boba-brown-sugar.webp';
import menuBobaUbe from '../../../assets/menu/coffee-story/boba-ube.webp';
import menuBobaStrawberry from '../../../assets/menu/coffee-story/boba-strawberry.webp';
import menuBobaThaiTea from '../../../assets/menu/coffee-story/boba-thai-tea.webp';
import menuBobaRoohAfza from '../../../assets/menu/coffee-story/boba-rooh-afza.webp';
import menuAdeStrawberry from '../../../assets/menu/coffee-story/ade-strawberry.webp';
import menuAdeMango from '../../../assets/menu/coffee-story/ade-mango.webp';
import menuAdeSunset from '../../../assets/menu/coffee-story/ade-sunset.webp';
import menuAdePassionFruit from '../../../assets/menu/coffee-story/ade-passion-fruit.webp';
import menuMidnightLychee from '../../../assets/menu/coffee-story/midnight-lychee.webp';
import menuSmoothieStrawberryBanana from '../../../assets/menu/coffee-story/smoothie-strawberry-banana.webp';
import menuSmoothieMangoBanana from '../../../assets/menu/coffee-story/smoothie-mango-banana.webp';
import menuSmoothieStrawberryMango from '../../../assets/menu/coffee-story/smoothie-strawberry-mango.webp';
import menuSmoothieGreenMachine from '../../../assets/menu/coffee-story/smoothie-green-machine.webp';
import menuSmoothieBananaDate from '../../../assets/menu/coffee-story/smoothie-banana-date.webp';
import menuSandwichTeriyaki from '../../../assets/menu/coffee-story/sandwich-teriyaki.webp';
import menuWrapChickenCaesar from '../../../assets/menu/coffee-story/wrap-chicken-caesar.webp';
import menuPaniniMozzarella from '../../../assets/menu/coffee-story/panini-mozzarella.webp';
import menuSandwichVeggie from '../../../assets/menu/coffee-story/sandwich-veggie.webp';
import menuAvocadoToast from '../../../assets/menu/coffee-story/avocado-toast.webp';
import menuGrilledCheese from '../../../assets/menu/coffee-story/grilled-cheese.webp';
import menuToastedBagel from '../../../assets/menu/coffee-story/toasted-bagel.webp';
import menuStrawberryNutellaCroissant from '../../../assets/menu/coffee-story/strawberry-nutella-croissant.webp';
import menuCroissantCheeseHoney from '../../../assets/menu/coffee-story/croissant-cheese-honey.webp';
import menuHoneycombCheeseBread from '../../../assets/menu/coffee-story/honeycomb-cheese-bread.webp';
import menuHoneycombCondensed from '../../../assets/menu/coffee-story/honeycomb-condensed.webp';
import menuHoneycombBites from '../../../assets/menu/coffee-story/honeycomb-bites.webp';
import menuMilkCake from '../../../assets/menu/coffee-story/milk-cake.webp';
import menuMochiDonut from '../../../assets/menu/coffee-story/mochi-donut.webp';

export const TENANT_MENU_MEDIA: Readonly<Record<string, number>> = {
  'espresso': menuEspresso,
  'americano': menuAmericano,
  'latte': menuLatte,
  'cappuccino': menuCappuccino,
  'flat-white': menuFlatWhite,
  'cortado': menuCortado,
  'macchiato': menuMacchiato,
  'mocha': menuMocha,
  'cold-brew': menuColdBrew,
  'frappe': menuFrappe,
  'tiramisu-latte': menuTiramisuLatte,
  'spanish-latte': menuSpanishLatte,
  'pistachio-latte': menuPistachioLatte,
  'ube-latte': menuUbeLatte,
  'honey-lavender-latte': menuHoneyLavenderLatte,
  'honey-rose-latte': menuHoneyRoseLatte,
  'brown-sugar-shaken-espresso': menuBrownSugarShakenEspresso,
  'biscoff-latte': menuBiscoffLatte,
  'spanish-oat-shaken': menuSpanishOatShaken,
  'libyan-nescafe': menuLibyanNescafe,
  'turkish-coffee': menuTurkishCoffee,
  'loose-leaf-tea': menuLooseLeafTea,
  'chai-latte': menuChaiLatte,
  'london-fog': menuLondonFog,
  'matcha-latte': menuMatchaLatte,
  'strawberry-matcha': menuStrawberryMatcha,
  'ube-matcha': menuUbeMatcha,
  'orange-blossom-matcha': menuOrangeBlossomMatcha,
  'honey-lavender-matcha': menuHoneyLavenderMatcha,
  'spanish-matcha': menuSpanishMatcha,
  'adeni-chai': menuAdeniChai,
  'boba-milk-tea': menuBobaMilkTea,
  'boba-brown-sugar': menuBobaBrownSugar,
  'boba-ube': menuBobaUbe,
  'boba-strawberry': menuBobaStrawberry,
  'boba-thai-tea': menuBobaThaiTea,
  'boba-rooh-afza': menuBobaRoohAfza,
  'ade-strawberry': menuAdeStrawberry,
  'ade-mango': menuAdeMango,
  'ade-sunset': menuAdeSunset,
  'ade-passion-fruit': menuAdePassionFruit,
  'midnight-lychee': menuMidnightLychee,
  'smoothie-strawberry-banana': menuSmoothieStrawberryBanana,
  'smoothie-mango-banana': menuSmoothieMangoBanana,
  'smoothie-strawberry-mango': menuSmoothieStrawberryMango,
  'smoothie-green-machine': menuSmoothieGreenMachine,
  'smoothie-banana-date': menuSmoothieBananaDate,
  'sandwich-teriyaki': menuSandwichTeriyaki,
  'wrap-chicken-caesar': menuWrapChickenCaesar,
  'panini-mozzarella': menuPaniniMozzarella,
  'sandwich-veggie': menuSandwichVeggie,
  'avocado-toast': menuAvocadoToast,
  'grilled-cheese': menuGrilledCheese,
  'toasted-bagel': menuToastedBagel,
  'strawberry-nutella-croissant': menuStrawberryNutellaCroissant,
  'croissant-cheese-honey': menuCroissantCheeseHoney,
  'honeycomb-cheese-bread': menuHoneycombCheeseBread,
  'honeycomb-condensed': menuHoneycombCondensed,
  'honeycomb-bites': menuHoneycombBites,
  'milk-cake': menuMilkCake,
  'mochi-donut': menuMochiDonut,
};
