/**
 * The product cut-outs this tenant has seated.
 *
 * GENERATED by `pnpm onboard --tenant coffee-story --apply` from
 * `tenants/coffee-story/assets/products/`.
 *
 * A menu slug missing from this map is not an error: `resolveProductMedia`
 * returns null and the shelf is one row shorter, so a tenant part-way through
 * shooting its menu still boots.
 */
import cutoutAdeniChai from '../../../assets/products/coffee-story/adeni-chai.webp';
import cutoutChaiLatte from '../../../assets/products/coffee-story/chai-latte.webp';
import cutoutHoneyLavenderMatcha from '../../../assets/products/coffee-story/honey-lavender-matcha.webp';
import cutoutLondonFog from '../../../assets/products/coffee-story/london-fog.webp';
import cutoutLooseLeafTea from '../../../assets/products/coffee-story/loose-leaf-tea.webp';
import cutoutMatchaLatte from '../../../assets/products/coffee-story/matcha-latte.webp';
import cutoutOrangeBlossomMatcha from '../../../assets/products/coffee-story/orange-blossom-matcha.webp';
import cutoutSpanishMatcha from '../../../assets/products/coffee-story/spanish-matcha.webp';
import cutoutStrawberryMatcha from '../../../assets/products/coffee-story/strawberry-matcha.webp';
import cutoutUbeMatcha from '../../../assets/products/coffee-story/ube-matcha.webp';

/** menu slug -> Metro module id. The one place a cut-out asset is named. */
export const BUNDLED_CUTOUTS: Readonly<Record<string, number>> = {
  'adeni-chai': cutoutAdeniChai,
  'chai-latte': cutoutChaiLatte,
  'honey-lavender-matcha': cutoutHoneyLavenderMatcha,
  'london-fog': cutoutLondonFog,
  'loose-leaf-tea': cutoutLooseLeafTea,
  'matcha-latte': cutoutMatchaLatte,
  'orange-blossom-matcha': cutoutOrangeBlossomMatcha,
  'spanish-matcha': cutoutSpanishMatcha,
  'strawberry-matcha': cutoutStrawberryMatcha,
  'ube-matcha': cutoutUbeMatcha,
};
