import { StyleSheet } from 'react-native';

import type { BrandTokens } from '@platform/ui';

export const createStyles = (tokens: BrandTokens) => StyleSheet.create({
  page: { backgroundColor: tokens.surface },
  content: { gap: tokens.spacing.lg },
  pressed: { opacity: 0.72 },

  searchField: {
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.md,
    paddingHorizontal: tokens.spacing.lg,
    borderRadius: tokens.radius.pill,
    backgroundColor: tokens.surfaceElevated,
  },
  searchInput: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },

  locationCard: {
    minHeight: 96,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
    padding: tokens.spacing.lg,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surfaceElevated,
    shadowColor: tokens.textPrimary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: tokens.elevation.card, shadowRadius: 24, elevation: 5,
  },
  locationMark: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.surface,
  },
  locationCopy: { flex: 1, gap: 4 },
  locationName: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  locationBadges: { flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md, flexWrap: 'wrap' },
  statusBadge: { paddingHorizontal: tokens.spacing.md, paddingVertical: 2, borderRadius: tokens.radius.pill },
  statusBadgeOpen: { backgroundColor: tokens.surface },
  statusBadgeShut: { backgroundColor: tokens.surface },
  statusText: { fontFamily: tokens.fontBody, fontSize: 11 },
  statusTextOpen: { color: tokens.warning },
  statusTextShut: { color: tokens.textMuted },
  locationNote: { flex: 1, color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 11 },
  locationAddress: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 13, lineHeight: 18 },

  savedAddress: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
    padding: tokens.spacing.lg,
    borderRadius: tokens.radius.lg,
    borderWidth: 1,
    borderColor: tokens.surface,
    backgroundColor: tokens.surface,
  },

  sectionLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 18, marginTop: tokens.spacing.md },
  windowGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: tokens.spacing.md },
  windowChip: {
    minWidth: '47%',
    flexGrow: 1,
    minHeight: 62,
    justifyContent: 'center',
    paddingHorizontal: tokens.spacing.lg,
    borderRadius: tokens.radius.lg,
    borderWidth: 1,
    borderColor: tokens.surface,
    backgroundColor: tokens.surfaceElevated,
    gap: 2,
  },
  windowChipSelected: { borderColor: tokens.primary, backgroundColor: tokens.surface },
  windowDay: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12 },
  windowDaySelected: { color: tokens.primary },
  windowTime: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  windowTimeSelected: { color: tokens.textPrimary },

  field: { gap: tokens.spacing.sm },
  fieldRow: { flexDirection: 'row', gap: tokens.spacing.md },
  cityField: { flex: 1 },
  stateField: { width: 84 },
  fieldLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 13 },
  input: {
    minHeight: 52,
    borderRadius: tokens.radius.lg,
    borderWidth: 1,
    borderColor: tokens.secondary,
    backgroundColor: tokens.surfaceElevated,
    color: tokens.textPrimary,
    fontFamily: tokens.fontBody,
    fontSize: 16,
    paddingHorizontal: tokens.spacing.lg,
  },
  multiline: { minHeight: 88, paddingTop: tokens.spacing.lg, textAlignVertical: 'top' },
  inputClearable: { paddingRight: 48 },
  clearButton: {
    position: 'absolute',
    right: tokens.spacing.md,
    top: 0,
    bottom: 0,
    width: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressPreview: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: tokens.spacing.md,
    padding: tokens.spacing.lg,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surface,
  },
  addressPreviewText: { flex: 1, color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 18 },
  error: { color: tokens.danger, fontFamily: tokens.fontBody, fontSize: 13, lineHeight: 19 },
});
