import { StyleSheet } from 'react-native';


import { type BrandTokens } from '@platform/ui';


export const createStyles = (tokens: BrandTokens) => StyleSheet.create({
  cancelBlock: { marginHorizontal: tokens.spacing.xl, gap: tokens.spacing.sm },
  cancelRow: {
    borderRadius: tokens.radius.lg,
    borderWidth: 1,
    borderColor: tokens.secondary,
    backgroundColor: tokens.surfaceElevated,
    paddingVertical: tokens.spacing.lg,
    alignItems: 'center',
  },
  cancelText: { color: tokens.danger, fontFamily: tokens.fontBody, fontSize: 15 },
  cancelNote: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13, textAlign: 'center' },
  cancelError: { color: tokens.danger, fontFamily: tokens.fontBody, fontSize: 13, textAlign: 'center' },
  trackCard: {
    marginHorizontal: tokens.spacing.xl,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surfaceElevated,
    padding: tokens.spacing.xl,
    gap: tokens.spacing.lg,
  },
  trackRow: { flexDirection: 'row', gap: tokens.spacing.lg, alignItems: 'flex-start' },
  trackDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    marginTop: 3,
    backgroundColor: tokens.secondary,
  },
  trackDotReached: { backgroundColor: tokens.success },
  trackDotCurrent: { borderWidth: 3, borderColor: tokens.surface, width: 16, height: 16, borderRadius: 8, marginTop: 1 },
  trackCopy: { flex: 1, gap: 2 },
  trackTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  trackMuted: { color: tokens.textMuted },
  trackDetail: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
  page: { backgroundColor: tokens.surface },
  content: { gap: tokens.spacing.xl },
  contentCompact: { paddingHorizontal: tokens.spacing.lg, gap: tokens.spacing.lg },
  cardPressed: { transform: [{ scale: 0.975 }] },

  modeRow: { flexDirection: 'row', gap: tokens.spacing.lg },
  modeRowCompact: { gap: tokens.spacing.md },
  modeCard: {
    flex: 1,
    minHeight: 238,
    borderRadius: tokens.radius.lg,
    borderWidth: 2,
    borderColor: tokens.surfaceElevated,
    backgroundColor: tokens.surfaceElevated,
    padding: tokens.spacing.lg,
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: tokens.textPrimary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: tokens.elevation.card, shadowRadius: 24, elevation: 5,
  },
  modeCardCompact: { minHeight: 206, borderRadius: tokens.radius.lg, padding: tokens.spacing.md },
  modeCardSelected: { borderColor: tokens.primary, backgroundColor: tokens.surface },
  modeLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 22, lineHeight: 28 },
  modeLabelCompact: { fontSize: 19, lineHeight: 24 },

  hubRow: {
    minHeight: 76,
    borderRadius: tokens.radius.lg,
    borderWidth: 1,
    borderColor: tokens.surface,
    backgroundColor: tokens.surface,
    paddingHorizontal: tokens.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
  },
  hubIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.accent,
  },
  hubCopy: { flex: 1, gap: 3 },
  hubTitle: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  hubDetail: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 17 },

  promo: {
    minHeight: 104,
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacing.lg,
    padding: tokens.spacing.lg,
    borderRadius: tokens.radius.lg,
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.accent,
  },
  promoCopy: { flex: 1, gap: 4 },
  promoTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 22, lineHeight: 26 },
  promoDetail: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 13, lineHeight: 18 },
  promoMark: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.surfaceElevated,
  },

  illustration: { flex: 1, width: '100%', minHeight: 154, alignItems: 'center', justifyContent: 'center' },
  illustrationCompact: { minHeight: 132 },
  routeLine: { position: 'absolute', left: 14, right: 14, top: '58%', height: 2, backgroundColor: tokens.surface },
  routePin: { position: 'absolute', top: '54%', width: 10, height: 10, borderRadius: 5, backgroundColor: tokens.secondary },
  routePinStart: { left: 12 },
  routePinEnd: { right: 12 },
  car: { width: 72, height: 58, alignItems: 'center', justifyContent: 'center' },
  shopSign: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.surface,
    borderWidth: 1,
    borderColor: tokens.accent,
    marginBottom: -8,
  },
  shopSignCompact: { width: 46, height: 46, borderRadius: 23 },
  shopSignActive: { backgroundColor: tokens.surface, borderColor: tokens.secondary },
  shopBuilding: {
    width: 124,
    minHeight: 94,
    borderWidth: 2,
    borderColor: tokens.textPrimary,
    backgroundColor: tokens.surface,
    borderRadius: tokens.radius.md,
    overflow: 'hidden',
  },
  shopBuildingCompact: { width: 102, minHeight: 84 },
  shopBuildingActive: { backgroundColor: tokens.surface },
  shopRoof: { height: 22, backgroundColor: tokens.secondary, borderBottomWidth: 2, borderBottomColor: tokens.textPrimary },
  shopWindows: { flex: 1, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-evenly', padding: tokens.spacing.md },
  shopWindow: { width: 24, height: 30, borderWidth: 1.5, borderColor: tokens.textPrimary, backgroundColor: tokens.surfaceElevated },
  shopDoor: { width: 28, height: 48, borderWidth: 1.5, borderColor: tokens.textPrimary, backgroundColor: tokens.surface },

  placedCard: { borderRadius: tokens.radius.lg, backgroundColor: tokens.surfaceElevated, padding: tokens.spacing.xl, gap: tokens.spacing.md, shadowColor: tokens.textPrimary, shadowOffset: { width: 0, height: 8 }, shadowOpacity: tokens.elevation.card, shadowRadius: 24, elevation: 5 },
  placedMark: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: tokens.success,
  },
  placedTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 28, lineHeight: 34 },
  placedDetail: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15, lineHeight: 22 },
  placedSummary: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13, lineHeight: 19 },
  placedTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingTop: tokens.spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: tokens.secondary,
  },
  placedTotalLabel: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  placedTotalValue: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 18 },
  placedNote: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12, lineHeight: 18 },
});
