/**
 * The generated barrels that let a guest app hold every applied tenant at once.
 *
 * Metro cannot `require` a path it computes at runtime, which is why the tenant
 * used to be one shared checked-in file that the last `--apply` overwrote --
 * onboard brand B and brand A's build inputs were gone from the tree. A barrel
 * is the way out: every path in it is a literal, so it is as static as Metro
 * needs, while naming N tenants instead of one.
 *
 * Two barrels rather than one, deliberately. `index.ts` carries only JSON, so
 * it stays reachable from `node:test` without an asset transform (the rule the
 * whole domain layer depends on); `media.ts` carries the `.webp` import maps
 * and is imported only from the view layer.
 */
import { readdirSync, existsSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { isPlatformSlug } from '@platform/schema';

export type GuestApp = 'customer' | 'kiosk';

/** Both guest binaries. The operator app is tenant-by-login and has no slot. */
export const GUEST_APPS: readonly GuestApp[] = ['customer', 'kiosk'];

/** Only the customer app ships product cut-outs; the kiosk has no shelf. */
export function shipsProductMedia(app: GuestApp): boolean {
  return app === 'customer';
}

export function slotsDirectory(root: string, app: GuestApp): string {
  return join(root, 'apps', app, 'src', 'tenants');
}

/**
 * The tenants applied to this app, read from the tree rather than a list.
 *
 * The directory is the truth: a slug is applied when its folder holds a brand
 * file. Deriving the barrel from the tree is what makes `--apply` additive and
 * idempotent -- applying B regenerates a barrel that still names A.
 */
export function appliedSlugs(root: string, app: GuestApp): readonly string[] {
  const directory = slotsDirectory(root, app);
  if (!existsSync(directory)) return [];
  const slugs = readdirSync(directory, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() && existsSync(join(directory, entry.name, 'brand.json')))
    .map((entry) => entry.name)
    .sort();
  // Every slug here is interpolated into generated TypeScript and into
  // applied.json, which app.config.ts joins into a path. A directory name is
  // not a validated value just because onboarding usually writes it, so the
  // generator refuses rather than emitting whatever the tree happens to hold.
  for (const slug of slugs) {
    if (!isPlatformSlug(slug)) {
      throw new Error(
        `apps/${app}/src/tenants/${slug} is not a kebab-case tenant slug. `
        + 'Remove or rename it; the generated barrel names each slug literally.',
      );
    }
  }
  return slugs;
}

/** `coffee-story` -> `CoffeeStory`, for a generated identifier. */
function pascal(slug: string): string {
  return slug.split(/[^a-z0-9]+/i)
    .filter((part) => part.length > 0)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('');
}

const DO_NOT_EDIT = 'GENERATED by `pnpm onboard --tenant <slug> --apply`. Do not edit.';
const TENANT_ARTWORK = [
  'gift/birthday-cake.webp', 'gift/birthday-confetti.webp', 'gift/congrats-bloom.webp',
  'gift/congrats-gold.webp', 'gift/grateful.webp', 'gift/healing-oil.webp',
  'gift/quiet-hour.webp', 'gift/thank-you.webp', 'hero/home-hero.mp4',
  'hero/stones.webp', 'rewards/liquid-nebula.webp',
] as const;

function renderConfigBarrel(app: GuestApp, slugs: readonly string[]): string {
  const imports = slugs.flatMap((slug) => [
    `import brand${pascal(slug)} from './${slug}/brand.json';`,
    `import menu${pascal(slug)} from './${slug}/menu.json';`,
    `import modules${pascal(slug)} from './${slug}/modules.json';`,
  ]);
  const entries = slugs.map((slug) => `  '${slug}': {
    slug: '${slug}',
    brand: brand${pascal(slug)},
    modules: modules${pascal(slug)},
    menu: menu${pascal(slug)},
  },`);
  return `/**
 * Every tenant this checkout has applied, and the one this build is for.
 *
 * ${DO_NOT_EDIT}
 *
 * Asset-free on purpose: only JSON is imported here, so \`node:test\` can reach
 * anything that reads a tenant without a \`.webp\` transform. The static import
 * maps live in ./media.ts.
 *
 * \`EXPO_PUBLIC_TENANT\` picks the tenant and is inlined into the bundle at
 * build time (publicly readable, which a slug is fine to be). Unset with one
 * tenant applied resolves to it; unset with several throws right here, because
 * a build that guesses ships one shop's menu under another shop's name.
 */
import { selectTenantSlot, type TenantSlotIdentity } from '@platform/domain';

${imports.join('\n')}${imports.length > 0 ? '\n' : ''}
export type TenantSlot = TenantSlotIdentity & {
  readonly brand: unknown;
  readonly modules: unknown;
  readonly menu: unknown;
};

/** Applied slugs, sorted. More than one is the point of this layout. */
export const APPLIED_TENANT_SLUGS: readonly string[] = [${slugs.map((slug) => `'${slug}'`).join(', ')}];

const SLOTS: Readonly<Record<string, TenantSlot>> = {
${entries.join('\n')}${entries.length > 0 ? '\n' : ''}};

export const TENANT_SLOT: TenantSlot = selectTenantSlot({
  app: '${app}',
  slots: SLOTS,
  requested: process.env.EXPO_PUBLIC_TENANT,
});

export const TENANT_SLUG: string = TENANT_SLOT.slug;
`;
}

function renderMediaBarrel(app: GuestApp, slugs: readonly string[]): string {
  const cutouts = shipsProductMedia(app);
  const artwork = app === 'customer';
  const imports = slugs.flatMap((slug) => [
    `import { TENANT_MENU_MEDIA as menuMedia${pascal(slug)} } from './${slug}/menu-media.generated';`,
    ...(cutouts ? [`import { BUNDLED_CUTOUTS as cutouts${pascal(slug)} } from './${slug}/product-media.generated';`] : []),
    `import brandLogo${pascal(slug)} from '../../assets/tenants/${slug}/brand/logo.png';`,
    ...(artwork ? TENANT_ARTWORK.map((path) => `import artwork${pascal(slug)}${pascal(path)} from '../../assets/tenants/${slug}/${path}';`) : []),
  ]);
  const entries = slugs.map((slug) => `  '${slug}': {
    brandLogo: brandLogo${pascal(slug)},
    ${artwork ? `artwork: {${TENANT_ARTWORK.map((path) => `\n      '${path}': artwork${pascal(slug)}${pascal(path)},`).join('')}\n    },\n    ` : ''}menuMedia: menuMedia${pascal(slug)},${cutouts ? `\n    productMedia: cutouts${pascal(slug)},` : ''}
  },`);
  const productField = cutouts ? '\n  readonly productMedia: Readonly<Record<string, number>>;' : '';
  const artworkField = artwork
    ? `  readonly artwork: Readonly<Record<${TENANT_ARTWORK.map((path) => `'${path}'`).join(' | ')}, number>>;\n`
    : '';
  return `/**
 * The static image maps for every applied tenant, and the one this build uses.
 *
 * ${DO_NOT_EDIT}
 *
 * Separate from ./index.ts because this file reaches \`.webp\` modules: the
 * config barrel has to stay importable from \`node:test\`, this one does not.
 * The slug is resolved once, there, so both barrels can never disagree.
 */
import { TENANT_SLUG } from './index';

${imports.join('\n')}${imports.length > 0 ? '\n' : ''}
export type TenantMediaSlot = {
  readonly brandLogo: number;
${artworkField}  readonly menuMedia: Readonly<Record<string, number>>;${productField}
};

const MEDIA: Readonly<Record<string, TenantMediaSlot>> = {
${entries.join('\n')}${entries.length > 0 ? '\n' : ''}};

// Object.hasOwn and not a bare index: a slug is a key into a plain object, so
// an inherited property name would otherwise read as a bundled tenant.
const selected = Object.hasOwn(MEDIA, TENANT_SLUG) ? MEDIA[TENANT_SLUG] : undefined;
if (!selected) {
  throw new Error(\`apps/${app} has no bundled media for "\${TENANT_SLUG}". Re-run \\\`pnpm onboard --tenant \${TENANT_SLUG} --apply\\\`.\`);
}

export const TENANT_MEDIA: TenantMediaSlot = selected;
`;
}

/**
 * Rewrites both barrels and the applied manifest for one app.
 *
 * `applied.json` exists so `app.config.ts` can answer "which tenants are in
 * this tree" without parsing TypeScript. The Expo config resolves the same
 * slug by the same rule; a drift test pins the two answers together.
 */
export function regenerateBarrels(root: string, app: GuestApp): readonly string[] {
  const slugs = appliedSlugs(root, app);
  const directory = slotsDirectory(root, app);
  writeFileSync(join(directory, 'index.ts'), renderConfigBarrel(app, slugs));
  writeFileSync(join(directory, 'media.ts'), renderMediaBarrel(app, slugs));
  writeFileSync(
    join(directory, 'applied.json'),
    `${JSON.stringify({ $generated: DO_NOT_EDIT, slugs }, null, 2)}\n`,
  );
  return slugs;
}
