/**
 * `--apply`, made additive: one directory per tenant instead of one shared file.
 *
 * What this replaces was a genuine blocker on a second franchisee. The old step
 * copied brand.json, modules.json, menu.json and the generated import maps over
 * checked-in files both guest apps shared, so applying brand B deleted brand
 * A's build inputs -- commit it and A's released binary was no longer
 * reproducible from any commit; refuse to commit and the drift guard failed.
 *
 * Everything written here is keyed by slug, including the menu photographs and
 * the product cut-outs: two tenants can and do name the same item (`cortado`
 * is on both shipped menus), so a flat asset directory is a byte collision, not
 * just untidy.
 *
 * What is deliberately NOT per-slug: the app icon, splash, adaptive icon,
 * favicon and web manifest. Those are named at fixed paths by app.config.ts and
 * by native build config, and one binary carries exactly one of each -- see
 * scripts/onboard-app-artwork.ts.
 */
import { copyFileSync, existsSync, mkdirSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import {
  appliedSlugs,
  GUEST_APPS,
  regenerateBarrels,
  shipsProductMedia,
  slotsDirectory,
  type GuestApp,
} from './onboard-tenant-barrel.js';

/** An empty manifest resolves to no capabilities, which is what "none declared" means. */
const NO_MODULES = `${JSON.stringify({ modules: [] }, null, 2)}\n`;

/**
 * Mirrors one asset directory, removing what the tenant no longer ships.
 *
 * Scoped to this tenant's own subdirectory, which is what makes the removal
 * safe: the previous shared-directory version of this deleted the *other*
 * tenant's photographs whenever a tenant without photography was applied.
 */
function syncAssets(from: string, to: string, extensions: readonly string[]): number {
  mkdirSync(to, { recursive: true });
  const sources = existsSync(from)
    ? readdirSync(from).filter((file) => extensions.some((extension) => file.endsWith(extension)))
    : [];
  const wanted = new Set(sources);
  for (const file of readdirSync(to)) {
    if (extensions.some((extension) => file.endsWith(extension)) && !wanted.has(file)) {
      unlinkSync(join(to, file));
    }
  }
  for (const file of sources) copyFileSync(join(from, file), join(to, file));
  return sources.length;
}

function menuIdentifier(itemSlug: string): string {
  return `menu${itemSlug.split('-').map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`).join('')}`;
}

function cutoutIdentifier(itemSlug: string): string {
  return `cutout${itemSlug.split('-').map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`).join('')}`;
}

function renderMenuMedia(slug: string, itemSlugs: readonly string[]): string {
  const imports = itemSlugs.map(
    (item) => `import ${menuIdentifier(item)} from '../../../assets/menu/${slug}/${item}.webp';`,
  );
  const entries = itemSlugs.map((item) => `  '${item}': ${menuIdentifier(item)},`);
  return `/** GENERATED by \`pnpm onboard --tenant ${slug} --apply\`. */
${imports.join('\n')}${imports.length > 0 ? '\n' : ''}
export const TENANT_MENU_MEDIA: Readonly<Record<string, number>> = {
${entries.join('\n')}${entries.length > 0 ? '\n' : ''}};
`;
}

function renderProductMedia(slug: string, cutoutSlugs: readonly string[]): string {
  const imports = cutoutSlugs.map(
    (item) => `import ${cutoutIdentifier(item)} from '../../../assets/products/${slug}/${item}.webp';`,
  );
  const entries = cutoutSlugs.map((item) => `  '${item}': ${cutoutIdentifier(item)},`);
  return `/**
 * The product cut-outs this tenant has seated.
 *
 * GENERATED by \`pnpm onboard --tenant ${slug} --apply\` from
 * \`tenants/${slug}/assets/products/\`.
 *
 * A menu slug missing from this map is not an error: \`resolveProductMedia\`
 * returns null and the shelf is one row shorter, so a tenant part-way through
 * shooting its menu still boots.
 */
${imports.join('\n')}${imports.length > 0 ? '\n' : ''}
/** menu slug -> Metro module id. The one place a cut-out asset is named. */
export const BUNDLED_CUTOUTS: Readonly<Record<string, number>> = {
${entries.join('\n')}${entries.length > 0 ? '\n' : ''}};
`;
}

function webpSlugs(directory: string): readonly string[] {
  if (!existsSync(directory)) return [];
  return readdirSync(directory)
    .filter((file) => file.endsWith('.webp'))
    .map((file) => file.replace(/\.webp$/, ''))
    .sort();
}

export type TenantSlotApplication = {
  readonly root: string;
  readonly slug: string;
  readonly tenantDir: string;
  /** The compiled menu, already serialised, so both apps bundle the same bytes. */
  readonly menuJson: string;
  /** Menu item slugs in menu order; each needs one statically importable WebP. */
  readonly itemSlugs: readonly string[];
};

export type TenantSlotResult = {
  readonly menuAssets: number;
  readonly cutouts: readonly string[];
  readonly appliedByApp: Readonly<Record<GuestApp, readonly string[]>>;
};

/**
 * Writes this tenant's slot into both guest apps and regenerates the barrels.
 *
 * Idempotent: every file is rewritten from the tenant folder, and the barrels
 * are derived from the directory listing rather than appended to.
 */
export function applyTenantSlot(application: TenantSlotApplication): TenantSlotResult {
  const { root, slug, tenantDir, menuJson, itemSlugs } = application;
  const brandPath = join(tenantDir, 'brand.json');
  const modulesPath = join(tenantDir, 'modules.json');
  const cutouts = webpSlugs(join(tenantDir, 'assets', 'products'));

  let menuAssets = 0;
  for (const app of GUEST_APPS) {
    const slotDir = join(slotsDirectory(root, app), slug);
    mkdirSync(slotDir, { recursive: true });
    copyFileSync(brandPath, join(slotDir, 'brand.json'));
    if (existsSync(modulesPath)) {
      copyFileSync(modulesPath, join(slotDir, 'modules.json'));
    } else {
      writeFileSync(join(slotDir, 'modules.json'), NO_MODULES);
    }
    writeFileSync(join(slotDir, 'menu.json'), menuJson);
    writeFileSync(join(slotDir, 'menu-media.generated.ts'), renderMenuMedia(slug, itemSlugs));
    menuAssets = syncAssets(
      join(tenantDir, 'assets', 'menu'),
      join(root, 'apps', app, 'assets', 'menu', slug),
      ['.webp', '.normalized.json'],
    );
    if (shipsProductMedia(app)) {
      syncAssets(join(tenantDir, 'assets', 'products'), join(root, 'apps', app, 'assets', 'products', slug), ['.webp']);
      writeFileSync(join(slotDir, 'product-media.generated.ts'), renderProductMedia(slug, cutouts));
    }
  }

  const appliedByApp = {
    customer: regenerateBarrels(root, 'customer'),
    kiosk: regenerateBarrels(root, 'kiosk'),
  };
  return { menuAssets, cutouts, appliedByApp };
}

/** The tenant slugs each guest app currently bundles, for the CLI's own reporting. */
export function describeApplied(root: string): string {
  return GUEST_APPS.map((app) => `${app}: ${appliedSlugs(root, app).join(', ')}`).join('; ');
}
