/**
 * `--apply`, made additive: one directory per tenant instead of one shared file.
 *
 * What this replaces was a genuine blocker on a second franchisee. The old step
 * copied brand.json, modules.json, menu.json and the generated import maps over
 * checked-in files both guest apps shared, so applying brand B deleted brand
 * A's build inputs -- commit it and A's released binary was no longer
 * reproducible from any commit; refuse to commit and the drift guard failed.
 *
 * Everything written here is keyed by slug, including the menu photographs and
 * the product cut-outs: two tenants can and do name the same item (`cortado`
 * is on both shipped menus), so a flat asset directory is a byte collision, not
 * just untidy.
 *
 * App icons, splash, favicon and the web manifest are also per-slug, but their
 * generated source and native-specific layout live in onboard-app-artwork.ts.
 */
import { copyFileSync, existsSync, lstatSync, mkdirSync, readdirSync, unlinkSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { isPlatformSlug } from '@platform/schema';

import {
  appliedSlugs,
  GUEST_APPS,
  regenerateBarrels,
  shipsProductMedia,
  slotsDirectory,
  type GuestApp,
} from './onboard-tenant-barrel.js';
import { reconcileTenantSlots } from './lib/onboard-guest-reconciliation.js';

/**
 * Refuses a name that must not reach generated source or a filesystem path.
 *
 * Menu item slugs arrive validated; product cut-outs do not -- their names are
 * read straight off disk, deliberately tolerating extras, and land in two
 * interpolations inside `product-media.generated.ts`. `barista's pick.webp` is
 * a legal filename that would corrupt the module it is written into, and a
 * franchisee photography drop is where such a name comes from. Checked at the
 * point of use, because the generator is what turns a filename into code.
 */
function assertSlug(value: string, what: string): string {
  if (!isPlatformSlug(value)) {
    throw new Error(
      `${what} "${value}" is not kebab-case. Rename it to lowercase letters, digits and single hyphens `
      + 'before applying; it is written into generated TypeScript and into an asset path.',
    );
  }
  return value;
}

/** An empty manifest resolves to no capabilities, which is what "none declared" means. */
const NO_MODULES = `${JSON.stringify({ modules: [] }, null, 2)}\n`;

/**
 * Mirrors one asset directory, removing what the tenant no longer ships.
 *
 * Scoped to this tenant's own subdirectory, which is what makes the removal
 * safe: the previous shared-directory version of this deleted the *other*
 * tenant's photographs whenever a tenant without photography was applied.
 */
function syncAssets(from: string, to: string, extensions: readonly string[]): number {
  mkdirSync(to, { recursive: true });
  // `isFile()` via lstat, not stat: `copyFileSync` follows symlinks, so a link
  // named `x.webp` in a tenant folder would copy arbitrary host content into a
  // shipped bundle. A tenant asset is a real file or it is not synced.
  const sources = existsSync(from)
    ? readdirSync(from).filter((file) => extensions.some((extension) => file.endsWith(extension))
        && lstatSync(join(from, file)).isFile())
    : [];
  const wanted = new Set(sources);
  for (const file of readdirSync(to)) {
    if (extensions.some((extension) => file.endsWith(extension)) && !wanted.has(file)) {
      unlinkSync(join(to, file));
    }
  }
  for (const file of sources) copyFileSync(join(from, file), join(to, file));
  return sources.length;
}

function menuIdentifier(itemSlug: string): string {
  return `menu${itemSlug.split('-').map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`).join('')}`;
}

function cutoutIdentifier(itemSlug: string): string {
  return `cutout${itemSlug.split('-').map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`).join('')}`;
}

function renderMenuMedia(slug: string, itemSlugs: readonly string[]): string {
  for (const item of itemSlugs) assertSlug(item, 'menu item');
  const imports = itemSlugs.map(
    (item) => `import ${menuIdentifier(item)} from '../../../assets/menu/${slug}/${item}.webp';`,
  );
  const entries = itemSlugs.map((item) => `  '${item}': ${menuIdentifier(item)},`);
  return `/** GENERATED by \`pnpm onboard --tenant ${slug} --apply\`. */
${imports.join('\n')}${imports.length > 0 ? '\n' : ''}
export const TENANT_MENU_MEDIA: Readonly<Record<string, number>> = {
${entries.join('\n')}${entries.length > 0 ? '\n' : ''}};
`;
}

function renderProductMedia(slug: string, cutoutSlugs: readonly string[]): string {
  for (const item of cutoutSlugs) assertSlug(item, 'product cut-out');
  const imports = cutoutSlugs.map(
    (item) => `import ${cutoutIdentifier(item)} from '../../../assets/products/${slug}/${item}.webp';`,
  );
  const entries = cutoutSlugs.map((item) => `  '${item}': ${cutoutIdentifier(item)},`);
  return `/**
 * The product cut-outs this tenant has seated.
 *
 * GENERATED by \`pnpm onboard --tenant ${slug} --apply\` from
 * \`tenants/${slug}/assets/products/\`.
 *
 * A menu slug missing from this map is not an error: \`resolveProductMedia\`
 * returns null and the shelf is one row shorter, so a tenant part-way through
 * shooting its menu still boots.
 */
${imports.join('\n')}${imports.length > 0 ? '\n' : ''}
/** menu slug -> Metro module id. The one place a cut-out asset is named. */
export const BUNDLED_CUTOUTS: Readonly<Record<string, number>> = {
${entries.join('\n')}${entries.length > 0 ? '\n' : ''}};
`;
}

function webpSlugs(directory: string): readonly string[] {
  if (!existsSync(directory)) return [];
  return readdirSync(directory)
    .filter((file) => file.endsWith('.webp'))
    .map((file) => file.replace(/\.webp$/, ''))
    .sort();
}

export type TenantSlotApplication = {
  readonly root: string;
  readonly slug: string;
  readonly tenantDir: string;
  /** The compiled menu, already serialised, so both apps bundle the same bytes. */
  readonly menuJson: string;
  /** Menu item slugs in menu order; each needs one statically importable WebP. */
  readonly itemSlugs: readonly string[];
  /** Exact guest binaries this tenant declares in brand.json surfaces. */
  readonly surfaces?: readonly GuestApp[];
};

export type TenantSlotResult = {
  readonly menuAssets: number;
  readonly cutouts: readonly string[];
  readonly appliedByApp: Readonly<Record<GuestApp, readonly string[]>>;
};

/**
 * Writes this tenant's slot into both guest apps and regenerates the barrels.
 *
 * Idempotent: every file is rewritten from the tenant folder, and the barrels
 * are derived from the directory listing rather than appended to.
 */
export function applyTenantSlot(application: TenantSlotApplication): TenantSlotResult {
  const { root, slug, tenantDir, menuJson, itemSlugs, surfaces = GUEST_APPS } = application;
  assertSlug(slug, 'tenant slug');
  const brandPath = join(tenantDir, 'brand.json');
  const modulesPath = join(tenantDir, 'modules.json');
  const cutouts = webpSlugs(join(tenantDir, 'assets', 'products'));

  let menuAssets = 0;
  for (const app of surfaces) {
    const slotDir = join(slotsDirectory(root, app), slug);
    mkdirSync(slotDir, { recursive: true });
    copyFileSync(brandPath, join(slotDir, 'brand.json'));
    if (existsSync(modulesPath)) {
      copyFileSync(modulesPath, join(slotDir, 'modules.json'));
    } else {
      writeFileSync(join(slotDir, 'modules.json'), NO_MODULES);
    }
    writeFileSync(join(slotDir, 'menu.json'), menuJson);
    writeFileSync(join(slotDir, 'menu-media.generated.ts'), renderMenuMedia(slug, itemSlugs));
    menuAssets += syncAssets(
      join(tenantDir, 'assets', 'menu'),
      join(root, 'apps', app, 'assets', 'menu', slug),
      ['.webp', '.normalized.json'],
    );
    if (shipsProductMedia(app)) {
      syncAssets(join(tenantDir, 'assets', 'products'), join(root, 'apps', app, 'assets', 'products', slug), ['.webp']);
      writeFileSync(join(slotDir, 'product-media.generated.ts'), renderProductMedia(slug, cutouts));
    }
  }

  reconcileTenantSlots(root, slug, surfaces);

  const appliedByApp = {
    customer: regenerateBarrels(root, 'customer'),
    kiosk: regenerateBarrels(root, 'kiosk'),
  };
  return { menuAssets, cutouts, appliedByApp };
}

/** The tenant slugs each guest app currently bundles, for the CLI's own reporting. */
export function describeApplied(root: string): string {
  return GUEST_APPS.map((app) => `${app}: ${appliedSlugs(root, app).join(', ')}`).join('; ');
}
