import { StyleSheet } from 'react-native';

import {
  BLEED, GLASS_BOX_HEIGHT, GLASS_BOX_WIDTH, GLASS_INSET_X, GLASS_TOP,
  GROUND_HEIGHT, GROUND_TOP, SHADOW_BOTTOM, SHADOW_HEIGHT, SHADOW_INSET_X,
  SHADOW_WIDTH, SLOT_HEIGHT, SLOT_WIDTH,
} from '@/features/glass-feature';
import { alpha, type BrandTokens } from '@platform/ui';

export const createHomeStyles = (tokens: BrandTokens) => StyleSheet.create({
  dropSection: { gap: 0 },
  dropBlurb: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13, lineHeight: 18 },
  dropArchiveLink: { alignSelf: 'center', marginTop: tokens.spacing.lg, paddingVertical: tokens.spacing.sm, paddingHorizontal: tokens.spacing.lg },
  dropArchiveText: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14, textDecorationLine: 'underline' },
  shell: { flex: 1 },
  screen: { backgroundColor: tokens.surface },
  content: { paddingTop: 0, paddingHorizontal: 0, paddingBottom: 150, gap: 0 },
  hero: { width: '100%', backgroundColor: tokens.surface, overflow: 'hidden' },
  heroSlide: { height: '100%', overflow: 'hidden' },
  heroMedia: { position: 'absolute', top: 0, bottom: 0, left: '-14%', right: '-14%' },
  openingContent: { position: 'absolute', left: tokens.spacing.xl, right: tokens.spacing.xl, bottom: 42 },
  bookNowPill: { alignSelf: 'center', minHeight: 46, borderRadius: tokens.radius.pill, backgroundColor: tokens.primary, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: tokens.spacing.md, paddingHorizontal: tokens.spacing.xl, },
  bookNowText: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 15 },
  bookNowDivider: { width: 1, height: 16, backgroundColor: 'rgba(255,255,255,0.35)' },
  bookNowWait: { color: 'rgba(255,255,255,0.82)', fontFamily: tokens.fontBody, fontSize: 13 },
  pulseWrap: { width: 12, height: 12, alignItems: 'center', justifyContent: 'center' },
  pulseRing: { position: 'absolute', width: 12, height: 12, borderRadius: 8, backgroundColor: tokens.success },
  pulseCore: { width: 7, height: 7, borderRadius: 5, backgroundColor: tokens.success },
  pressed: { opacity: 0.85 },
  dots: { position: 'absolute', left: tokens.spacing.xl, bottom: 19, flexDirection: 'row', gap: 6 },
  dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: 'rgba(255,255,255,0.55)' },
  dotActive: { width: 22, backgroundColor: tokens.surfaceElevated },
  packagePanel: { position: 'absolute', left: tokens.spacing.lg, right: tokens.spacing.lg, bottom: 42, borderRadius: tokens.radius.lg, borderWidth: 1, borderColor: 'rgba(255,255,255,0.78)', backgroundColor: alpha(tokens.surfaceElevated, 0.94), padding: tokens.spacing.lg, },
  packageHeadingRow: { minHeight: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  storyEyebrowDark: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 10, letterSpacing: 1.2, textTransform: 'uppercase' },
  packageTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 22, lineHeight: 27 },
  packageArrow: { width: 44, height: 44, borderRadius: tokens.radius.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: tokens.surface },
  packageRow: { minHeight: 38, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md, borderTopWidth: 1, borderTopColor: tokens.secondary },
  packageCopy: { flex: 1, minWidth: 0 },
  packageName: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 13 },
  packageDetail: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 10, marginTop: 1 },
  packagePrice: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 13 },
  storyContent: { position: 'absolute', left: tokens.spacing.xl, right: tokens.spacing.xl, bottom: 52, gap: tokens.spacing.md, alignItems: 'flex-start' },
  storyEyebrow: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 11, letterSpacing: 1.4, textTransform: 'uppercase' },
  storyTitle: { maxWidth: 310, color: tokens.surfaceElevated, fontFamily: tokens.fontDisplay, fontSize: 38, lineHeight: 41, letterSpacing: -1 },
  storyBody: { maxWidth: 300, color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 14, lineHeight: 20 },
  storyButton: { minHeight: 46, borderRadius: tokens.radius.pill, backgroundColor: tokens.surfaceElevated, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.md, paddingHorizontal: tokens.spacing.xl },
  storyButtonText: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  sectionHeader: { paddingHorizontal: tokens.spacing.xl, paddingTop: tokens.spacing.xxl, gap: tokens.spacing.sm },
  pill: { alignSelf: 'flex-start', borderRadius: tokens.radius.md, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.md, paddingVertical: 5, },
  pillText: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 13 },
  sectionTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 40, lineHeight: 44, letterSpacing: -1.2, },
  sectionBody: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16, lineHeight: 23 },
  feature: { minHeight: 200, marginTop: tokens.spacing.xl, flexDirection: 'row', alignItems: 'center' },
  featureFlip: { flexDirection: 'row-reverse' },
  featureImage: { width: 164, height: 186 },
  featureImageLeft: { marginLeft: -32, borderTopRightRadius: 999, borderBottomRightRadius: 999 },
  featureImageRight: { marginRight: -32, borderTopLeftRadius: 999, borderBottomLeftRadius: 999 },
  featureCopy: { flex: 1, paddingHorizontal: tokens.spacing.xl, gap: 6 },
  tag: { alignSelf: 'flex-start', borderRadius: tokens.radius.md, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.md, paddingVertical: 4, },
  tagText: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 12 },
  featureTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 26, lineHeight: 30, letterSpacing: -0.6, },
  featureFrom: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 14 },
  glassFeature: { minHeight: SLOT_HEIGHT },
  glassSlot: { width: SLOT_WIDTH, height: SLOT_HEIGHT },
  glassSlotLeft: { marginLeft: -BLEED },
  glassSlotRight: { marginRight: -BLEED },
  glassGround: { position: 'absolute', left: 0, right: 0, top: GROUND_TOP, height: GROUND_HEIGHT, overflow: 'hidden', },
  glassGroundLeft: { borderTopRightRadius: 999, borderBottomRightRadius: 999 },
  glassGroundRight: { borderTopLeftRadius: 999, borderBottomLeftRadius: 999 },
  glassShadow: { position: 'absolute', bottom: SHADOW_BOTTOM, width: SHADOW_WIDTH, height: SHADOW_HEIGHT, borderRadius: 999, backgroundColor: tokens.secondary, },
  glassShadowLeft: { left: SHADOW_INSET_X },
  glassShadowRight: { right: SHADOW_INSET_X },
  glassLift: { position: 'absolute', top: GLASS_TOP, width: GLASS_BOX_WIDTH, height: GLASS_BOX_HEIGHT },
  glassLiftLeft: { left: GLASS_INSET_X },
  glassLiftRight: { right: GLASS_INSET_X },
  glassImage: { width: GLASS_BOX_WIDTH, height: GLASS_BOX_HEIGHT },
  learnMore: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15, marginTop: 2 },
  categorySection: { paddingTop: tokens.spacing.xl },
  categoryHeader: { paddingHorizontal: tokens.spacing.xl, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.lg, },
  categoryHeaderCopy: { flex: 1, minWidth: 0, gap: 2 },
  categoryTitle: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 26, lineHeight: 30, letterSpacing: -0.5 },
  categoryTagline: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
  categoryCount: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 13, backgroundColor: tokens.surface, borderRadius: tokens.radius.pill, paddingHorizontal: tokens.spacing.md, paddingVertical: 4, overflow: 'hidden', },
  menuList: { paddingHorizontal: tokens.spacing.xl, paddingTop: tokens.spacing.md },
  menuRow: { minHeight: 76, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.lg, borderBottomWidth: 1, borderBottomColor: tokens.secondary, paddingVertical: tokens.spacing.md, },
  menuRowCopy: { flex: 1, minWidth: 0, gap: 2 },
  menuRowName: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 15 },
  menuRowBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 12.5 },
  menuRowPrice: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 17 },
  showAllButton: { alignSelf: 'center', marginTop: tokens.spacing.md, minHeight: 44, borderRadius: tokens.radius.pill, backgroundColor: tokens.surface, borderWidth: 1, borderColor: tokens.surface, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.sm, paddingHorizontal: tokens.spacing.xl, },
  showAllText: { color: tokens.primary, fontFamily: tokens.fontBody, fontSize: 14 },
  addOns: { paddingHorizontal: tokens.spacing.xl, paddingTop: tokens.spacing.lg, gap: tokens.spacing.md },
  addOnRow: { minHeight: 66, borderRadius: tokens.radius.lg, backgroundColor: tokens.surface, paddingHorizontal: tokens.spacing.lg, flexDirection: 'row', alignItems: 'center', gap: tokens.spacing.lg, },
  addOnCopy: { flex: 1, gap: 2 },
  addOnName: { color: tokens.textPrimary, fontFamily: tokens.fontBody, fontSize: 16 },
  addOnBody: { color: tokens.textMuted, fontFamily: tokens.fontBody, fontSize: 13 },
  addOnPrice: { color: tokens.textPrimary, fontFamily: tokens.fontDisplay, fontSize: 19 },
  siriWrap: { paddingHorizontal: tokens.spacing.xl, paddingTop: tokens.spacing.xxl },
  footerCtaSpace: { height: tokens.spacing.xxl + 48 },
  stickyCtaWrap: { position: 'absolute', left: tokens.spacing.xl, right: tokens.spacing.xl, zIndex: 40, alignItems: 'center', },
  stickyBookNowButton: { minHeight: 46, borderRadius: tokens.radius.pill, backgroundColor: tokens.primary, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: tokens.spacing.md, paddingHorizontal: tokens.spacing.xl, },
  stickyBookNowText: { color: tokens.surfaceElevated, fontFamily: tokens.fontBody, fontSize: 15, },
  stickyBookNowWait: { color: 'rgba(255,255,255,0.82)', fontFamily: tokens.fontBody, fontSize: 13, },
});
